/**
 * Certified static project updates registry — PP008 read model source of truth.
 * Publishing console deferred to PP012. Not a social feed.
 */
import type { RegistryProjectUpdateRecord } from './types'

export const PROJECT_UPDATES_REGISTRY: RegistryProjectUpdateRecord[] = [
  {
    stableKey: 'melega-dex.canonical-project-page-identity',
    projectSlug: 'melega-dex',
    version: '1.0.0',
    publishedAt: '2026-07-18T16:00:00.000Z',
    updatedAt: '2026-07-18T16:00:00.000Z',
    authorType: 'MELEGA',
    authorIdentity: 'melega',
    title: 'Canonical Project Page identity published',
    summary: 'Melega DEX now exposes a machine-readable Project Page identity document with verified registry fields.',
    content:
      'The Melega DEX Project Page identity shell is the canonical public profile for this project. It publishes sanitized display name, purpose, supported chains, assets, deployments, and declared capabilities under schema melega.project-page.v1. This event establishes the permanent project identity surface used by subsequent evidence, readiness, markets, and participation layers.',
    category: 'PRODUCT_RELEASE',
    affectedCapabilities: ['machineManifest', 'tradable'],
    affectedDeployments: ['eip155:56'],
    affectedAssets: ['token://56/0x963556de0eb8138E97A85F0A86eE0acD159D210b'],
    affectedContracts: [],
    evidenceClaimTypes: ['PROJECT_IDENTITY', 'PROJECT_NAME', 'OFFICIAL_WEBSITE'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    visibility: 'PUBLIC',
    status: 'ACTIVE',
    supersedesStableKey: null,
    machineTags: ['project-page', 'identity', 'pp001', 'canonical'],
  },
  {
    stableKey: 'melega-dex.provenance-evidence-framework',
    projectSlug: 'melega-dex',
    version: '1.0.0',
    publishedAt: '2026-07-19T12:00:00.000Z',
    updatedAt: '2026-07-19T12:00:00.000Z',
    authorType: 'MELEGA',
    authorIdentity: 'melega',
    title: 'Project provenance and evidence framework live',
    summary:
      'Public evidence claims for identity, official resources, and contracts are now attached to the Project Page.',
    content:
      'The Project Provenance and Evidence Framework (PP002) publishes public evidence records with deterministic evidence IDs, freshness, and verification levels. Trust surfaces consume these records without inventing safety ratings. This update records the operational availability of the evidence pack for Melega DEX.',
    category: 'DOCUMENTATION',
    affectedCapabilities: ['machineManifest'],
    affectedDeployments: ['eip155:56'],
    affectedAssets: [],
    affectedContracts: [],
    evidenceClaimTypes: ['PROJECT_IDENTITY', 'OFFICIAL_DOCUMENTATION', 'MELEGA_VERIFICATION'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    visibility: 'PUBLIC',
    status: 'ACTIVE',
    supersedesStableKey: null,
    machineTags: ['evidence', 'pp002', 'provenance'],
  },
  {
    stableKey: 'melega-dex.markets-orchestration',
    projectSlug: 'melega-dex',
    version: '1.0.0',
    publishedAt: '2026-07-20T14:00:00.000Z',
    updatedAt: '2026-07-20T14:00:00.000Z',
    authorType: 'MELEGA',
    authorIdentity: 'melega',
    title: 'Swap and markets orchestration available',
    summary:
      'Project Page Participate exposes certified Melega DEX markets with deep links into the existing Swap surface.',
    content:
      'Markets orchestration attributes spot LP venues to Melega DEX and opens the certified trade destination. No second swap UI is introduced. MARCO/WBNB on BSC remains the preferred market when READY. This is an operational capability event, not a price or volume announcement.',
    category: 'MARKET_AVAILABILITY',
    affectedCapabilities: ['tradable', 'liquidity'],
    affectedDeployments: ['eip155:56'],
    affectedAssets: ['token://56/0x963556de0eb8138E97A85F0A86eE0acD159D210b'],
    affectedContracts: ['0x7286c16c3c05d4c17b689be7948ec4fa4e861d1e'],
    evidenceClaimTypes: ['ASSET_IDENTITY', 'SUPPORTED_CHAIN'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    visibility: 'PUBLIC',
    status: 'ACTIVE',
    supersedesStableKey: null,
    machineTags: ['markets', 'swap', 'pp005', 'bsc'],
  },
  {
    stableKey: 'melega-dex.liquidity-building-discovery',
    projectSlug: 'melega-dex',
    version: '1.0.0',
    publishedAt: '2026-07-20T22:00:00.000Z',
    updatedAt: '2026-07-20T22:00:00.000Z',
    authorType: 'MELEGA',
    authorIdentity: 'melega',
    title: 'Liquidity Building discovery exposed on Project Page',
    summary:
      'Liquidity Building is discoverable as a project capability with activation currently blocked in certified deployment inputs.',
    content:
      'Project Page orchestration exposes Liquidity Building via the certified destination /liquidity-studio?view=building. Execution remains inside Liquidity Building V1. Certified deployment readiness is BLOCKED; the destination remains available for discovery and setup. This update does not authorize activation or execution.',
    category: 'LIQUIDITY_BUILDING',
    affectedCapabilities: ['liquidity'],
    affectedDeployments: ['eip155:56'],
    affectedAssets: [],
    affectedContracts: [],
    evidenceClaimTypes: ['SUPPORTED_CHAIN', 'DEPLOYMENT_IDENTITY'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    visibility: 'PUBLIC',
    status: 'ACTIVE',
    supersedesStableKey: 'melega-dex.liquidity-building-preview-notice',
    machineTags: ['liquidity-building', 'pp007', 'activation-blocked'],
  },
  {
    stableKey: 'melega-dex.liquidity-building-preview-notice',
    projectSlug: 'melega-dex',
    version: '1.0.0',
    publishedAt: '2026-07-19T18:00:00.000Z',
    updatedAt: '2026-07-20T22:00:00.000Z',
    authorType: 'MELEGA',
    authorIdentity: 'melega',
    title: 'Liquidity Building preview notice (superseded)',
    summary: 'Earlier preview notice that Liquidity Building would appear on the Project Page.',
    content:
      'This notice stated that Liquidity Building discovery would be wired into the Project Page. It is superseded by the certified Liquidity Building discovery update and remains in the timeline for chronology.',
    category: 'ROADMAP',
    affectedCapabilities: ['liquidity'],
    affectedDeployments: ['eip155:56'],
    affectedAssets: [],
    affectedContracts: [],
    evidenceClaimTypes: ['SUPPORTED_CHAIN'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    visibility: 'PUBLIC',
    status: 'SUPERSEDED',
    supersedesStableKey: null,
    machineTags: ['liquidity-building', 'superseded', 'roadmap'],
  },
  {
    stableKey: 'melega-dex.participation-farms-pools',
    projectSlug: 'melega-dex',
    version: '1.0.0',
    publishedAt: '2026-07-20T20:00:00.000Z',
    updatedAt: '2026-07-20T20:00:00.000Z',
    authorType: 'MELEGA',
    authorIdentity: 'melega',
    title: 'Liquidity, farms, and pools participation surfaces linked',
    summary: 'Participate lists certified liquidity pools, farms, and staking pools with studio deep links only.',
    content:
      'Participation orchestration attributes venue-registered liquidity pools, farms, and staking pools to Melega DEX. Destinations open Liquidity Studio, Farms, and Pools without embedding APR, TVL, or execution payloads on the Project Page.',
    category: 'LIQUIDITY',
    affectedCapabilities: ['liquidity', 'farm', 'pool'],
    affectedDeployments: ['eip155:56'],
    affectedAssets: ['token://56/0x963556de0eb8138E97A85F0A86eE0acD159D210b'],
    affectedContracts: ['0x41D5487836452d23f2c467070244E5842B412794', '0x7286c16c3c05d4c17b689be7948ec4fa4e861d1e'],
    evidenceClaimTypes: ['ASSET_IDENTITY', 'CONTRACT_IDENTITY'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    visibility: 'PUBLIC',
    status: 'ACTIVE',
    supersedesStableKey: null,
    machineTags: ['participation', 'farms', 'pools', 'pp006'],
  },
  {
    stableKey: 'melega-dex.archived-legacy-import-note',
    projectSlug: 'melega-dex',
    version: '1.0.0',
    publishedAt: '2026-07-10T10:00:00.000Z',
    updatedAt: '2026-07-18T16:00:00.000Z',
    authorType: 'AUTOMATED_RUNTIME',
    authorIdentity: 'runtime:project-registry',
    title: 'Legacy registry import baseline archived',
    summary: 'Archived baseline note from the static MVP registry import phase.',
    content:
      'Melega DEX entered the project registry as a legacy_import / mvpStatic record. This baseline note is archived after the canonical Project Page identity event and is retained for timeline completeness.',
    category: 'INFRASTRUCTURE',
    affectedCapabilities: ['machineManifest'],
    affectedDeployments: [],
    affectedAssets: [],
    affectedContracts: [],
    evidenceClaimTypes: ['PROJECT_LIFECYCLE_STATUS'],
    provenanceSourceClass: 'DERIVED',
    visibility: 'PUBLIC',
    status: 'ARCHIVED',
    supersedesStableKey: null,
    machineTags: ['archive', 'legacy-import', 'registry'],
  },
  {
    stableKey: 'melega-dex.retracted-draft-activation-claim',
    projectSlug: 'melega-dex',
    version: '1.0.0',
    publishedAt: '2026-07-19T20:30:00.000Z',
    updatedAt: '2026-07-20T22:05:00.000Z',
    authorType: 'MELEGA',
    authorIdentity: 'melega',
    title: 'Draft Liquidity Building activation claim retracted',
    summary:
      'A draft claim that Liquidity Building was production-active has been retracted; activation remains blocked.',
    content:
      'This draft entry incorrectly suggested Liquidity Building production activation. It is retracted. Certified deployment inputs remain BLOCKED. History is retained; do not treat this entry as current.',
    category: 'SECURITY_NOTICE',
    affectedCapabilities: ['liquidity'],
    affectedDeployments: ['eip155:56'],
    affectedAssets: [],
    affectedContracts: [],
    evidenceClaimTypes: ['SUPPORTED_CHAIN'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    visibility: 'PUBLIC',
    status: 'RETRACTED',
    supersedesStableKey: null,
    machineTags: ['retracted', 'liquidity-building', 'activation'],
  },
]

export function listRegistryUpdatesForSlug(slug: string): RegistryProjectUpdateRecord[] {
  return PROJECT_UPDATES_REGISTRY.filter((row) => row.projectSlug === slug).map((row) => ({
    ...row,
    affectedCapabilities: [...row.affectedCapabilities],
    affectedDeployments: [...row.affectedDeployments],
    affectedAssets: [...row.affectedAssets],
    affectedContracts: [...row.affectedContracts],
    evidenceClaimTypes: [...row.evidenceClaimTypes],
    machineTags: [...row.machineTags],
  }))
}
