import { describe, expect, it } from 'vitest'
import { readFileSync } from 'fs'
import path from 'path'
import { GLOBAL_HEADER_NAV } from 'app-shell/config/globalHeaderNav'
import { shellBottomNavItems } from 'app-shell/config/navigation'

const WEB = path.resolve(__dirname, '../..')
const load = (relativePath: string) => readFileSync(path.resolve(WEB, relativePath), 'utf8')

describe('Recovery Wave 2 — performance and one-click funnels', () => {
  it('pins tokens to this workspace so another worktree cannot duplicate runtime dependencies', () => {
    const config = readFileSync(path.resolve(WEB, '../next.config.mjs'), 'utf8')
    expect(config).toContain("path.resolve(webRoot, '../../packages/tokens')")
    expect(config).toContain("'@pancakeswap/tokens': localTokensPackage")
  })

  it('preserves early primary-nav taps while keeping normal transitions soft', () => {
    const app = load('pages/_app.tsx')
    const fullApp = load('app-runtime/FullMyApp.tsx')
    const guard = load('lib/navigation/preserveEarlyNavigation.ts')
    const bottomNav = load('design-system/melega/components/BottomNavigation/MelegaBottomNavigation.tsx')
    expect(app).toContain("dynamic(() => import('app-runtime/FullMyApp')")
    expect(app).toContain('{ ssr: true }')
    expect(guard).toContain("document.readyState === 'complete'")
    expect(guard).toContain("dataset.melegaHydrated === 'true'")
    expect(fullApp).toContain("dataset.melegaHydrated = 'true'")
    expect(guard).toContain('window.location.assign(href)')
    expect(bottomNav).toContain('preserveEarlyNavigation(event, item.href)')
  })

  it('loads the personal dashboard only after intent and only while open', () => {
    const shell = load('app-shell/MelegaAppShell.tsx')
    const provider = load('components/MyMelega/MyMelegaProvider.tsx')
    const header = load('design-system/melega/components/GlobalHeader/MelegaGlobalHeader.tsx')
    expect(provider).toContain("import('./MyMelegaDrawer')")
    expect(shell).toContain('dynamic(preloadMyMelegaDrawer')
    expect(shell).toContain('isMyMelegaOpen ? <MyMelegaDrawer /> : null')
    expect(header).toContain('onPointerEnter={preloadMyMelegaDrawer}')
    expect(header).toContain('onFocus={preloadMyMelegaDrawer}')
  })

  it('does not start seven-chain transaction watchers before a wallet exists', () => {
    const updaters = load('app-shell/GlobalUpdaters.tsx')
    const walletUpdaters = load('state/transactions/WalletTransactionUpdaters.tsx')
    expect(updaters).toContain("dynamic(() => import('state/transactions/WalletTransactionUpdaters')")
    expect(updaters).toContain("profile === 'transactional' && address ? <WalletTransactionUpdaters /> : null")
    expect(walletUpdaters).toContain('TransactionUpdater')
    expect(walletUpdaters).toContain('TreasuryHandoffUpdater')
  })

  it('keeps non-visual runtimes and heavyweight search data out of first paint', () => {
    const fullApp = load('app-runtime/FullMyApp.tsx')
    const updaters = load('app-shell/GlobalUpdaters.tsx')
    const search = load('app-shell/components/GlobalSearch.tsx')
    const wallet = load('components/ConnectWalletButton.tsx')
    expect(fullApp).toContain("dynamic(() => import('app-shell/GlobalRuntimeHooks')")
    expect(fullApp).toContain("dynamic(() => import('components/NetworkModal')")
    expect(fullApp).toContain('clientRuntimeReady ? <TransactionsDetailModal /> : null')
    expect(fullApp).toContain('globalRuntimeReady ? <GlobalRuntimeHooks')
    expect(updaters).toContain("dynamic(() => import('state/lists/updater')")
    expect(updaters).toContain("import('lib/kerl-constitutional')")
    expect(search).toContain("import('lib/global-search')")
    expect(search).toContain('void ensureSearchRuntime()')
    expect(search).toContain('const ResultMain = styled.a')
    expect(search).toContain('window.location.assign(target.href)')
    expect(search).not.toContain('router.push(href)')
    expect(wallet).toContain("import('@pancakeswap/ui-wallets')")
    expect(wallet).toContain('open ? (')
  })

  it('uses focused UIKit entry points for global providers instead of the full component barrel', () => {
    const fullApp = load('app-runtime/FullMyApp.tsx')
    const providers = load('Providers.tsx')
    expect(fullApp).toContain("from '@pancakeswap/uikit/src/ResetCSS'")
    expect(fullApp).toContain("from '@pancakeswap/uikit/src/components/ScrollToTopButton/ScrollToTopButtonV2'")
    expect(fullApp).toContain("from '@pancakeswap/uikit/src/contexts/ToastsContext/Listener'")
    expect(fullApp).not.toContain("from '@pancakeswap/uikit'")
    expect(providers).toContain("from '@pancakeswap/uikit/src/Providers'")
    expect(providers).toContain("from '@pancakeswap/uikit/src/widgets/Modal/ModalContext'")
    expect(providers).not.toContain("from '@pancakeswap/uikit'")
  })

  it('loads the animated modal runtime only after the first modal intent', () => {
    const modalContext = load('../../../packages/uikit/src/widgets/Modal/ModalContext.tsx')
    const modalRenderer = load('../../../packages/uikit/src/widgets/Modal/ModalRenderer.tsx')
    const modalV2 = load('../../../packages/uikit/src/widgets/Modal/ModalV2.tsx')
    expect(modalContext).toContain('React.lazy(() => import("./ModalRenderer"))')
    expect(modalContext).toContain('setRendererMounted(true)')
    expect(modalContext).toContain('rendererMounted ? (')
    expect(modalContext).not.toContain('from "framer-motion"')
    expect(modalRenderer).toContain('from "framer-motion"')
    expect(modalV2).toContain('from "./ModalWrapper"')
    expect(modalV2).not.toContain('from "framer-motion"')
  })

  it('keeps static Box consumers independent from the animation runtime', () => {
    const box = load('../../../packages/uikit/src/components/Box/Box.tsx')
    const motionBox = load('../../../packages/uikit/src/components/Box/MotionBox.tsx')
    const modalStyles = load('../../../packages/uikit/src/widgets/Modal/styles.tsx')
    expect(box).not.toContain('framer-motion')
    expect(motionBox).toContain('from "framer-motion"')
    expect(modalStyles).toContain('from "../../components/Box/Box"')
  })

  it('uses native CSS motion for static UIKit surfaces', () => {
    const tooltip = load('../../../packages/uikit/src/hooks/useTooltip/useTooltip.tsx')
    const styledTooltip = load('../../../packages/uikit/src/hooks/useTooltip/StyledTooltip.tsx')
    const skeleton = load('../../../packages/uikit/src/components/Skeleton/Skeleton.tsx')
    const submenu = load('../../../packages/uikit/src/components/SubMenuItems/SubMenuItems.tsx')
    expect(tooltip).not.toContain('framer-motion')
    expect(styledTooltip).not.toContain('framer-motion')
    expect(skeleton).not.toContain('framer-motion')
    expect(submenu).not.toContain('framer-motion')
    expect(styledTooltip).toContain('prefers-reduced-motion')
    expect(skeleton).toContain('prefers-reduced-motion')
  })

  it('preserves mobile modal swipe-to-close without a motion dependency', () => {
    const modal = load('../../../packages/uikit/src/widgets/Modal/Modal.tsx')
    const launchpadModal = load('../../../packages/uikit/src/widgets/Modal/ModalForLaunchpad.tsx')
    expect(modal).toContain('setPointerCapture(event.pointerId)')
    expect(modal).toContain('velocityY > MODAL_SWIPE_TO_CLOSE_VELOCITY')
    expect(modal).toContain('closest("[data-modal-drag-handle]")')
    expect(modal).not.toContain('dragSnapToOrigin')
    expect(modal).not.toContain('framer-motion')
    expect(launchpadModal).toContain('Container={ModalContainerForLaunchpad}')
    expect(launchpadModal).not.toContain('dragSnapToOrigin')
  })

  it('keeps blocklist safety immediate while blockchain updaters wait for idle time', () => {
    const fullApp = load('app-runtime/FullMyApp.tsx')
    const blocklist = load('app-shell/Blocklist.tsx')
    const constants = load('config/constants/index.ts')
    expect(fullApp).toContain("import Blocklist from 'app-shell/Blocklist'")
    expect(fullApp).toContain("dynamic(() => import('app-shell/GlobalUpdaters')")
    expect(fullApp).toContain('requestIdleCallback')
    expect(fullApp).toContain('{ timeout: 1200 }')
    expect(blocklist).toContain("from 'config/constants/blockedAddresses'")
    expect(blocklist).not.toContain("from 'config/constants'")
    expect(constants).toContain("export { BLOCKED_ADDRESSES } from './blockedAddresses'")
  })

  it('keeps Top Movers data out of first paint without splitting its shared snapshot', () => {
    const context = load('views/HomeTrade/TopMoversSnapshotContext.tsx')
    const runtime = load('views/HomeTrade/TopMoversSnapshotRuntime.tsx')
    expect(context).toContain("dynamic(() => import('./TopMoversSnapshotRuntime')")
    expect(context).toContain('requestIdleCallback')
    expect(context).toContain('{ timeout: 1600 }')
    expect(context).toContain('runtimeReady ? <TopMoversSnapshotRuntime')
    expect(context).not.toContain("from './useDexTrendingRankings'")
    expect(runtime).toContain("from './useDexTrendingRankings'")
    expect(runtime).toContain('onSnapshot(value)')
    expect(runtime).toContain('assertIdenticalPrefix(snapshot.entries, homeEntries)')
  })

  it('does not ship the full token list just to render a shell avatar', () => {
    const resolver = load('lib/token-logo/resolveTokenLogoSources.ts')
    const avatar = load('design-system/melega/components/MelegaTokenAvatar/MelegaTokenAvatar.tsx')
    expect(resolver).not.toContain('pancake-default.tokenlist.json')
    expect(resolver).not.toContain("from '@pancakeswap/sdk'")
    expect(resolver).toContain('getTokenLogoURLByAddress')
    expect(resolver).toContain('localBscTokenLogoCandidates')
    expect(avatar).toContain('logoURI')
    expect(avatar).toContain('data-token-logo-fallback="neutral-avatar"')
  })

  it('keeps global SEO metadata independent from farm, pool and contract runtimes', () => {
    const fullApp = load('app-runtime/FullMyApp.tsx')
    const page = load('components/Layout/Page.tsx')
    const meta = load('components/Layout/PageMeta.tsx')
    expect(fullApp).toContain("from 'components/Layout/PageMeta'")
    expect(fullApp).not.toContain("from 'components/Layout/Page'")
    expect(page).toContain("export { PageMeta } from './PageMeta'")
    expect(meta).toContain('Route metadata must stay deterministic and network-free')
    expect(meta).not.toContain('usePriceCakeBusd')
    expect(meta).not.toContain('state/farms')
    expect(meta).not.toContain('config/constants/pools')
    expect(meta).toContain('`${pageMetaTitle} | Melega DEX`')
    expect(meta).toContain('title ?? routeMeta?.title')
    expect(meta).toContain('description ?? routeMeta?.description')
  })

  it('renders the Home funnel before market and yield inventories start', () => {
    const home = load('views/HomeTrade/DexHomeScreen.tsx')
    const context = load('views/HomeTrade/HomeTradeDataContext.tsx')
    const runtime = load('views/HomeTrade/HomeTradeDataRuntime.tsx')
    expect(home).toContain('HomeTradeDataProvider')
    expect(home).toContain('useHomeCriticalData()')
    expect(home).not.toContain("from './useHomeTradeData'")
    expect(context).toContain("dynamic(() => import('./HomeTradeDataRuntime')")
    expect(context).toContain('timeout: 600')
    expect(context).toContain('startTransition(() => setRuntimeReady(true))')
    expect(context).toContain('runtimeReady ? <HomeTradeDataRuntime')
    expect(runtime).toContain("from './useHomeTradeData'")
    expect(runtime).toContain('onData(criticalData)')
  })

  it('serves one local premium typography system without render-blocking font providers', () => {
    const document = load('pages/_document.tsx')
    const fullApp = load('app-runtime/FullMyApp.tsx')
    const globalStyle = load('style/Global.tsx')
    const typography = load('design-system/melega/tokens/ds001/typography.ts')
    const economicShell = load('views/EconomicOS/components/EconomicPageShell.tsx')
    const economicActivation = load('views/EconomicActivation/NewProjectActivation.tsx')
    const legacyIlo = load('views/LegacyIloRetirement/LegacyIloRetirement.tsx')
    expect(document).not.toContain('fonts.googleapis.com')
    expect(document).not.toContain('Kanit')
    expect(fullApp).not.toContain('fonts.googleapis.com')
    expect(economicShell).not.toContain('fonts.googleapis.com')
    expect(economicActivation).not.toContain('fonts.googleapis.com')
    expect(legacyIlo).not.toContain('fonts.googleapis.com')
    expect(globalStyle).toContain("url('/fonts/inter/inter-v12-latin-regular.woff2')")
    expect(globalStyle).toContain("url('/fonts/relative/relative-book-pro.woff2')")
    expect(typography).toContain('Melega Relative')
    expect(typography).not.toContain('Sora')
  })

  it('uses the shared premium surface, focus, motion and popup language', () => {
    const globalStyle = load('style/Global.tsx')
    const uiOverrides = load('style/MelegaUIKitOverrides.tsx')
    const overlay = load('../../../packages/uikit/src/components/Overlay/Overlay.tsx')
    const modalStyles = load('../../../packages/uikit/src/widgets/Modal/styles.tsx')
    expect(globalStyle).toContain(':focus-visible')
    expect(globalStyle).toContain('prefers-reduced-motion')
    expect(uiOverrides).toContain("[data-premium-surface='true']")
    expect(uiOverrides).toContain("[role='dialog']")
    expect(uiOverrides).toContain('backdrop-filter: blur(20px)')
    expect(overlay).toContain('backdrop-filter: blur(8px)')
    expect(modalStyles).toContain('border-radius: 22px')
  })

  it('does not emit smart-router runtime code for type-only trade contracts', () => {
    const types = load('config/constants/types.ts')
    const routerFetch = load('state/swap/fetch/fetchBestPriceWithRouter.ts')
    expect(types).toContain("import type { TradeWithStableSwap } from '@pancakeswap/smart-router/evm'")
    expect(types).toContain("import type { StableTrade } from 'views/Swap/StableSwap/hooks/useStableTradeExactIn'")
    expect(routerFetch).toContain("import type { RouteType } from '@pancakeswap/smart-router/evm'")
  })

  it('boots Redux with lightweight yield reducers instead of RPC and inventory barrels', () => {
    const store = load('state/index.ts')
    const farmsReducer = load('state/farms/reducer.ts')
    const poolsReducer = load('state/pools/reducer.ts')
    expect(store).toContain("import farmsReducer from './farms/reducer'")
    expect(store).toContain("import poolsReducer from './pools/reducer'")
    expect(store).not.toContain("import farmsReducer from './farms'")
    expect(store).not.toContain("import poolsReducer from './pools'")
    expect(farmsReducer).not.toContain("from './fetchFarms'")
    expect(farmsReducer).not.toContain('masterchefABI')
    expect(poolsReducer).not.toContain("from 'config/constants/pools'")
    expect(poolsReducer).not.toContain('multicallv2')
  })

  it('loads secondary Swap and Liquidity tools only when their tabs need them', () => {
    const cockpit = load('views/Trade/TradeCockpit.tsx')
    const liquidity = load('views/LiquidityStudio/v3/LiquidityStudioV3Shell.tsx')
    expect(cockpit).toContain("dynamic(() => import('components/Menu/GlobalSettings/SettingsModal')")
    expect(cockpit).toContain("dynamic(() => import('./components/TradeHistoryPanel')")
    expect(cockpit).toContain("dynamic(() => import('./components/TradeRouterPanel')")
    expect(cockpit).toContain("dynamic(() => import('./components/TradeLimitOrdersPanel')")
    expect(liquidity).toContain("dynamic(() => import('../onePage/LiquidityBuildingCard')")
    expect(liquidity).toContain('window.setTimeout(() => setAiMounted(true), 500)')
  })

  it('defers token warning payloads while preserving certified Smart Swap execution ownership', () => {
    const warning = load('views/Swap/hooks/useWarningImport.tsx')
    const tradeWarning = load('views/Trade/hooks/useTradeWarningImport.tsx')
    expect(warning).toContain("dynamic(() => import('../components/SwapWarningModal')")
    expect(tradeWarning).toContain("dynamic(() => import('views/Swap/components/SwapWarningModal')")
    expect(warning).not.toContain('ImportTokenWarningModal')
    expect(tradeWarning).not.toContain('ImportTokenWarningModal')
  })

  it('keeps every core DEX funnel one click away on desktop and mobile', () => {
    expect(GLOBAL_HEADER_NAV.find((item) => item.id === 'swap')).toMatchObject({ href: '/swap' })
    expect(GLOBAL_HEADER_NAV.find((item) => item.id === 'liquidity')).toMatchObject({ href: '/liquidity' })
    expect(shellBottomNavItems.map((item) => item.id)).toEqual(['home', 'swap', 'liquidity', 'farms', 'pools'])
    expect(shellBottomNavItems.find((item) => item.id === 'swap')?.href).toBe('/swap')
    expect(shellBottomNavItems.find((item) => item.id === 'liquidity')?.href).toBe('/liquidity')
  })

  it('keeps the Swap terminal above the fold with compact premium rhythm', () => {
    const terminal = load('views/Trade/TradeTerminalScreen.tsx')
    expect(terminal).toContain('gap: ${tradeLayout.verticalRhythm}')
    expect(terminal).toContain("[data-studio-page-header='trade']")
    expect(terminal).toContain('min-height: 72px')
    expect(terminal).toContain('margin-bottom: 0')
  })

  it('Home quick actions avoid legacy aliases and redirects', () => {
    const quickActions = load('views/HomeTrade/HomeQuickActions.tsx')
    const homeData = load('views/HomeTrade/useHomeTradeData.ts')
    expect(quickActions).toContain("href: '/swap'")
    expect(quickActions).toContain("href: '/liquidity'")
    expect(quickActions).not.toContain("href: '/trade'")
    expect(homeData).not.toContain("href: '/trade'")
  })
})
