import {
  AiAgentExperienceAudit,
  EconomicJourneyAudit,
  ExperienceAuditScores,
  SurfaceExperienceAudit,
} from './experience-audit-types'

export const EXPERIENCE_AUDIT_VERSION = '0.1.0'

export const EXPERIENCE_AUDIT_AS_OF = '2026-06-29'

export const EXPERIENCE_AUDIT_BRANCH = 'mainnet-consolidation-m20'

export const EXPERIENCE_AUDIT_DISCLAIMER =
  'AI Agent Experience audit (D87) — read-only cognition and navigation analysis. No production logic, UI, or route changes.'

export const EXPERIENCE_AUDIT_SCORES: ExperienceAuditScores = {
  humanUx: 52,
  aiUx: 68,
  machineReadability: 74,
  economicFlow: 58,
  navigation: 45,
  civilizationConvergence: 62,
  d87Alignment: 61,
  overallD87: 60,
}

export const CRITICAL_FINDINGS = [
  'Global menu "Launch" points to /ilo (retired) — not /launch (capability read model)',
  'Homepage carousel still promotes /ilo as active launch pad; Mission 15 retirement not reflected in Home UX',
  'Homepage embeds legacy BabyMarco NFT mint UI — conflicts with Civilization Collectibles framing',
  '15+ Economic OS surfaces have no global menu entry — discoverable only via direct URL or cross-links',
  '/map is the best AI/human orientation surface but is not linked from menu or homepage',
  'melega-dex-manifest.json remains phase_2_pending placeholder — weak top-level agent discovery',
  'No .well-known entry for /map, /workspace, /identity, /launch, /execution, /readiness',
  'Workspace and Identity duplicate registry section listings — high information duplication for agents',
]

export const SURFACES_TO_MERGE = [
  'Graph + Query → single Registry Explorer hub for humans (keep separate manifests for agents)',
  'Identity → Workspace subsection or tab (preserve /identity route as alias)',
  'Events → Graph detail panel (preserve /events route)',
]

export const SURFACES_TO_RETIRE: string[] = [
  'None — no routes removed. Menu label "Launch" should alias to /launch; homepage /ilo CTA should retire visually.',
]

export const RECOMMENDED_HOMEPAGE_ARCHITECTURE = [
  'CORE: Swap, Liquidity, Farms, Pools, Surface Map (/map)',
  'SECONDARY: Launch (/launch), Workspace (/workspace), Projects (/projects)',
  'ADVANCED: Graph, Query, Presence, Execution, Identity, Collectibles, Activation (/new-project)',
  'HIDDEN: Legacy NFT mint block on home, ILO as primary CTA, external apply banner',
]

export const RECOMMENDED_MISSION_22 =
  'Mission 22: Navigation & Homepage Convergence — alias menu Launch→/launch, add Map/Workspace to menu or footer, remove homepage ILO/NFT mint prominence, publish unified .well-known discovery index pointing to /map and /registry/readiness/mainnet-gate.json. No global UI redesign; minimal additive wiring only.'

export const SURFACE_EXPERIENCE_AUDITS: SurfaceExperienceAudit[] = [
  {
    id: 'projects',
    route: '/projects',
    purposeClarity: 85,
    humanUnderstanding: 78,
    aiUnderstanding: 90,
    machineDiscoverability: 88,
    navigationRedundancy: 40,
    informationDuplication: 35,
    economicUsefulness: 80,
    executionUsefulness: 20,
    needToExist: true,
    betterHidden: false,
    betterPromoted: true,
    classification: 'read_model_only',
    inGlobalMenu: true,
    hasManifest: true,
    manifestUri: '/registry/projects/index.json',
    navigationRecommendation: 'keep',
    findings: ['In menu — good. Frozen Organ 01 contract.'],
  },
  {
    id: 'assets',
    route: '/assets',
    purposeClarity: 82,
    humanUnderstanding: 70,
    aiUnderstanding: 92,
    machineDiscoverability: 85,
    navigationRedundancy: 50,
    informationDuplication: 45,
    economicUsefulness: 85,
    executionUsefulness: 15,
    needToExist: true,
    betterHidden: false,
    betterPromoted: true,
    classification: 'read_model_only',
    inGlobalMenu: false,
    hasManifest: true,
    manifestUri: '/registry/assets/index.json',
    navigationRecommendation: 'promote',
    findings: ['Not in menu — agents find via graph/workspace only.'],
  },
  {
    id: 'venues',
    route: '/venues',
    purposeClarity: 75,
    humanUnderstanding: 65,
    aiUnderstanding: 88,
    machineDiscoverability: 82,
    navigationRedundancy: 55,
    informationDuplication: 50,
    economicUsefulness: 78,
    executionUsefulness: 25,
    needToExist: true,
    betterMerged: 'graph',
    betterHidden: false,
    betterPromoted: false,
    classification: 'read_model_only',
    inGlobalMenu: false,
    hasManifest: true,
    manifestUri: '/registry/venues/index.json',
    navigationRecommendation: 'move',
    findings: ['LP/farm venue index — overlaps workspace liquidity section.'],
  },
  {
    id: 'events',
    route: '/events',
    purposeClarity: 70,
    humanUnderstanding: 60,
    aiUnderstanding: 85,
    machineDiscoverability: 80,
    navigationRedundancy: 60,
    informationDuplication: 55,
    economicUsefulness: 70,
    executionUsefulness: 10,
    needToExist: true,
    betterMerged: 'graph',
    betterHidden: false,
    betterPromoted: false,
    classification: 'read_model_only',
    inGlobalMenu: false,
    hasManifest: true,
    manifestUri: '/registry/events/index.json',
    navigationRecommendation: 'merge',
    findings: ['Timeline layer — better as graph facet for humans.'],
  },
  {
    id: 'graph',
    route: '/graph',
    purposeClarity: 80,
    humanUnderstanding: 68,
    aiUnderstanding: 95,
    machineDiscoverability: 90,
    navigationRedundancy: 45,
    informationDuplication: 40,
    economicUsefulness: 88,
    executionUsefulness: 20,
    needToExist: true,
    betterHidden: false,
    betterPromoted: true,
    classification: 'read_model_only',
    inGlobalMenu: false,
    hasManifest: true,
    manifestUri: '/registry/graph/index.json',
    navigationRecommendation: 'promote',
    findings: ['Primary agent traversal surface — should be in secondary nav.'],
  },
  {
    id: 'query',
    route: '/query',
    purposeClarity: 72,
    humanUnderstanding: 55,
    aiUnderstanding: 90,
    machineDiscoverability: 85,
    navigationRedundancy: 65,
    informationDuplication: 60,
    economicUsefulness: 75,
    executionUsefulness: 15,
    needToExist: true,
    betterMerged: 'graph',
    betterHidden: false,
    betterPromoted: false,
    classification: 'read_model_only',
    inGlobalMenu: false,
    hasManifest: true,
    manifestUri: '/registry/query/index.json',
    navigationRecommendation: 'merge',
    findings: ['Agent-oriented — overlaps graph for humans.'],
  },
  {
    id: 'activation',
    route: '/new-project',
    purposeClarity: 78,
    humanUnderstanding: 62,
    aiUnderstanding: 82,
    machineDiscoverability: 80,
    navigationRedundancy: 50,
    informationDuplication: 45,
    economicUsefulness: 82,
    executionUsefulness: 5,
    needToExist: true,
    betterHidden: false,
    betterPromoted: false,
    classification: 'preview_only',
    inGlobalMenu: false,
    hasManifest: true,
    manifestUri: '/registry/activation/runtime.json',
    navigationRecommendation: 'move',
    findings: ['Preview activation — must not replace /launch as primary create path.'],
  },
  {
    id: 'execution',
    route: '/execution',
    purposeClarity: 70,
    humanUnderstanding: 50,
    aiUnderstanding: 85,
    machineDiscoverability: 78,
    navigationRedundancy: 55,
    informationDuplication: 35,
    economicUsefulness: 72,
    executionUsefulness: 40,
    needToExist: true,
    betterHidden: true,
    betterPromoted: false,
    classification: 'read_model_only',
    inGlobalMenu: false,
    hasManifest: true,
    manifestUri: '/registry/execution/index.json',
    navigationRecommendation: 'keep',
    findings: ['Illustrative only — agents must route to /swap for real execution.'],
  },
  {
    id: 'presence',
    route: '/presence',
    purposeClarity: 85,
    humanUnderstanding: 72,
    aiUnderstanding: 92,
    machineDiscoverability: 88,
    navigationRedundancy: 40,
    informationDuplication: 40,
    economicUsefulness: 90,
    executionUsefulness: 10,
    needToExist: true,
    betterHidden: false,
    betterPromoted: true,
    classification: 'read_model_only',
    inGlobalMenu: false,
    hasManifest: true,
    manifestUri: '/registry/presence/index.json',
    navigationRecommendation: 'promote',
    findings: ['Critical canonical vs presence distinction — high D87 value.'],
  },
  {
    id: 'launch',
    route: '/build-studio#build-import',
    purposeClarity: 88,
    humanUnderstanding: 75,
    aiUnderstanding: 90,
    machineDiscoverability: 85,
    navigationRedundancy: 70,
    informationDuplication: 50,
    economicUsefulness: 88,
    executionUsefulness: 35,
    needToExist: true,
    betterHidden: false,
    betterPromoted: true,
    classification: 'read_model_only',
    inGlobalMenu: false,
    hasManifest: true,
    manifestUri: '/registry/launch/index.json',
    navigationRecommendation: 'alias',
    findings: ['Menu "Launch" wrongly points to /ilo — critical navigation bug.'],
  },
  {
    id: 'workspace',
    route: '/command-center',
    purposeClarity: 90,
    humanUnderstanding: 80,
    aiUnderstanding: 88,
    machineDiscoverability: 82,
    navigationRedundancy: 75,
    informationDuplication: 80,
    economicUsefulness: 92,
    executionUsefulness: 15,
    needToExist: true,
    betterHidden: false,
    betterPromoted: true,
    classification: 'read_model_only',
    inGlobalMenu: false,
    hasManifest: true,
    manifestUri: '/registry/workspace/index.json',
    navigationRecommendation: 'promote',
    findings: ['Best human operator hub — duplicates child module links.'],
  },
  {
    id: 'collectibles',
    route: '/collectibles',
    purposeClarity: 82,
    humanUnderstanding: 70,
    aiUnderstanding: 86,
    machineDiscoverability: 84,
    navigationRedundancy: 45,
    informationDuplication: 30,
    economicUsefulness: 75,
    executionUsefulness: 20,
    needToExist: true,
    betterHidden: false,
    betterPromoted: false,
    classification: 'read_model_only',
    inGlobalMenu: false,
    hasManifest: true,
    manifestUri: '/registry/collectibles/index.json',
    navigationRecommendation: 'keep',
    findings: ['Reframes NFT — menu still has separate NFT block pointing to /nft.'],
  },
  {
    id: 'identity',
    route: '/identity',
    purposeClarity: 85,
    humanUnderstanding: 68,
    aiUnderstanding: 90,
    machineDiscoverability: 80,
    navigationRedundancy: 80,
    informationDuplication: 85,
    economicUsefulness: 80,
    executionUsefulness: 10,
    needToExist: true,
    betterMerged: 'workspace',
    betterHidden: false,
    betterPromoted: false,
    classification: 'read_model_only',
    inGlobalMenu: false,
    hasManifest: true,
    manifestUri: '/registry/identity/index.json',
    navigationRecommendation: 'merge',
    findings: ['High duplication with workspace sections — unique value is archetype/agent-readiness.'],
  },
  {
    id: 'map',
    route: '/map',
    purposeClarity: 95,
    humanUnderstanding: 85,
    aiUnderstanding: 98,
    machineDiscoverability: 90,
    navigationRedundancy: 20,
    informationDuplication: 25,
    economicUsefulness: 95,
    executionUsefulness: 10,
    needToExist: true,
    betterHidden: false,
    betterPromoted: true,
    classification: 'read_model_only',
    inGlobalMenu: false,
    hasManifest: true,
    manifestUri: '/registry/surfaces/index.json',
    navigationRecommendation: 'promote',
    findings: ['Canonical orientation surface — should be homepage secondary CTA and menu entry.'],
  },
  {
    id: 'swap',
    route: '/trade',
    purposeClarity: 95,
    humanUnderstanding: 95,
    aiUnderstanding: 90,
    machineDiscoverability: 70,
    navigationRedundancy: 10,
    informationDuplication: 5,
    economicUsefulness: 95,
    executionUsefulness: 100,
    needToExist: true,
    betterHidden: false,
    betterPromoted: true,
    classification: 'production_safe',
    inGlobalMenu: true,
    hasManifest: false,
    navigationRecommendation: 'keep',
    findings: ['Core DEX — menu wired correctly.'],
  },
  {
    id: 'liquidity',
    route: '/liquidity-studio',
    purposeClarity: 92,
    humanUnderstanding: 90,
    aiUnderstanding: 88,
    machineDiscoverability: 65,
    navigationRedundancy: 10,
    informationDuplication: 5,
    economicUsefulness: 92,
    executionUsefulness: 95,
    needToExist: true,
    betterHidden: false,
    betterPromoted: true,
    classification: 'production_safe',
    inGlobalMenu: true,
    hasManifest: false,
    navigationRecommendation: 'keep',
    findings: ['Under Trade submenu — correct.'],
  },
  {
    id: 'farms',
    route: '/farms',
    purposeClarity: 90,
    humanUnderstanding: 88,
    aiUnderstanding: 85,
    machineDiscoverability: 60,
    navigationRedundancy: 15,
    informationDuplication: 20,
    economicUsefulness: 88,
    executionUsefulness: 90,
    needToExist: true,
    betterHidden: false,
    betterPromoted: true,
    classification: 'production_safe',
    inGlobalMenu: true,
    hasManifest: false,
    navigationRecommendation: 'keep',
    findings: ['Earn menu — correct.'],
  },
  {
    id: 'pools',
    route: '/pools',
    purposeClarity: 88,
    humanUnderstanding: 85,
    aiUnderstanding: 85,
    machineDiscoverability: 60,
    navigationRedundancy: 15,
    informationDuplication: 20,
    economicUsefulness: 85,
    executionUsefulness: 88,
    needToExist: true,
    betterHidden: false,
    betterPromoted: true,
    classification: 'production_safe',
    inGlobalMenu: true,
    hasManifest: false,
    navigationRecommendation: 'keep',
    findings: ['Earn menu — correct. Homepage over-promotes pools carousels.'],
  },
  {
    id: 'ilo',
    route: '/ilo',
    purposeClarity: 90,
    humanUnderstanding: 75,
    aiUnderstanding: 88,
    machineDiscoverability: 85,
    navigationRedundancy: 90,
    informationDuplication: 60,
    economicUsefulness: 40,
    executionUsefulness: 0,
    needToExist: true,
    betterHidden: true,
    betterPromoted: false,
    classification: 'retired',
    inGlobalMenu: true,
    hasManifest: true,
    manifestUri: '/registry/legacy/ilo-retirement.json',
    navigationRecommendation: 'alias',
    findings: ['Retirement page correct — menu and homepage still treat as launch.'],
  },
  {
    id: 'nft_legacy',
    route: '/nft',
    purposeClarity: 70,
    humanUnderstanding: 75,
    aiUnderstanding: 72,
    machineDiscoverability: 55,
    navigationRedundancy: 65,
    informationDuplication: 70,
    economicUsefulness: 50,
    executionUsefulness: 80,
    needToExist: true,
    betterHidden: true,
    betterPromoted: false,
    classification: 'legacy_risky',
    inGlobalMenu: true,
    hasManifest: true,
    manifestUri: '/registry/collectibles/babymarco-genesis.json',
    navigationRecommendation: 'move',
    findings: ['Menu NFT + homepage mint duplicate /collectibles read model.'],
  },
]

export const ECONOMIC_JOURNEYS: EconomicJourneyAudit[] = [
  {
    persona: 'New Human User',
    journeyScore: 48,
    blockers: ['No /map on homepage', 'Launch menu → retired /ilo', 'NFT mint on home confuses purpose'],
    steps: [
      { step: 'Land on homepage', route: '/', status: 'broken', notes: 'Pancake-era layout; swap section + NFT mint + ILO banner' },
      { step: 'Connect Wallet', status: 'clear', notes: 'Global wallet button works' },
      { step: 'Understand Platform', route: '/map', status: 'missing', notes: 'No menu/home link to surface map' },
      { step: 'Create Project', route: '/projects', status: 'indirect', notes: 'Projects in menu but no create flow' },
      { step: 'Launch Asset', route: '/build-studio#build-import', status: 'broken', notes: 'Menu sends to /ilo retirement' },
      { step: 'Manage Economy', route: '/command-center', status: 'missing', notes: 'Not in menu' },
    ],
  },
  {
    persona: 'Existing Liquidity Provider',
    journeyScore: 72,
    blockers: ['Workspace/execution not in menu'],
    steps: [
      { step: 'Liquidity', route: '/liquidity-studio', status: 'clear', notes: 'Trade submenu' },
      { step: 'Workspace', route: '/command-center', status: 'missing', notes: 'Direct URL only' },
      { step: 'Execution', route: '/execution', status: 'indirect', notes: 'Cross-link from launch only' },
      { step: 'Identity', route: '/identity', status: 'indirect', notes: 'Cross-link from workspace' },
    ],
  },
  {
    persona: 'AI Agent',
    journeyScore: 76,
    blockers: ['Top-level manifest placeholder', 'No robots/sitemap for /map'],
    steps: [
      { step: 'Registry Discovery', route: '/registry/surfaces/index.json', status: 'clear', notes: 'Surface map manifest excellent' },
      { step: 'Graph', route: '/graph', status: 'clear', notes: 'Well-known + registry' },
      { step: 'Execution', route: '/execution', status: 'clear', notes: 'Must not execute here — illustrative' },
      { step: 'Workspace', route: '/command-center', status: 'clear', notes: 'Manifest indexed' },
      { step: 'Identity', route: '/identity', status: 'clear', notes: 'Agent-readiness score' },
      { step: 'Economic Decision', route: '/trade', status: 'clear', notes: 'Route to live execution' },
    ],
  },
  {
    persona: 'Project Creator',
    journeyScore: 55,
    blockers: ['Launch menu → /ilo', 'Activation preview not distinguished from launch'],
    steps: [
      { step: 'Launch', route: '/build-studio#build-import', status: 'broken', notes: 'Menu alias wrong' },
      { step: 'Activation', route: '/new-project', status: 'indirect', notes: 'Not in menu' },
      { step: 'Presence', route: '/presence', status: 'indirect', notes: 'Cross-links only' },
      { step: 'Workspace', route: '/command-center', status: 'missing', notes: 'Not in menu' },
    ],
  },
]

export const HOMEPAGE_TIERS: AiAgentExperienceAudit['homepageTiers'] = {
  core: ['Swap (/swap)', 'Liquidity (/liquidity)', 'Farms (/farms)', 'Pools (/pools)', 'Surface Map (/map)'],
  secondary: ['Launch (/launch)', 'Workspace (/workspace)', 'Projects (/projects)'],
  advanced: [
    'Graph (/graph)',
    'Query (/query)',
    'Presence (/presence)',
    'Execution (/execution)',
    'Identity (/identity)',
    'Collectibles (/collectibles)',
    'Activation (/new-project)',
  ],
  hidden: [
    'Homepage NFT mint block',
    'ILO carousel banner (/ilo)',
    'External apply banner',
    'Legacy Pancake metrics sections (if unused)',
  ],
}

export const NAVIGATION_RECOMMENDATIONS: AiAgentExperienceAudit['navigationRecommendations'] = [
  { surface: 'Launch', action: 'alias', rationale: 'Menu href /ilo → /launch; keep /ilo as legacy compat' },
  { surface: 'Map', action: 'promote', rationale: 'Add to menu or footer — primary orientation' },
  { surface: 'Workspace', action: 'promote', rationale: 'Operator hub — secondary menu item' },
  { surface: 'Assets', action: 'promote', rationale: 'Under Projects submenu or Registry group' },
  { surface: 'Graph', action: 'promote', rationale: 'Registry submenu for advanced users' },
  { surface: 'Presence', action: 'keep', rationale: 'Secondary — link from Launch/Workspace' },
  { surface: 'ILO', action: 'retire', rationale: 'Remove from menu primary; keep route + retirement page' },
  { surface: 'NFT', action: 'move', rationale: 'Nest under Collectibles or demote to legacy submenu' },
  { surface: 'Identity', action: 'merge', rationale: 'Tab within Workspace; keep /identity URL' },
  { surface: 'Query', action: 'merge', rationale: 'Into Graph for humans' },
  { surface: 'Events', action: 'merge', rationale: 'Into Graph timeline facet' },
  { surface: 'Venues', action: 'move', rationale: 'Registry submenu with Assets' },
  { surface: 'Execution', action: 'keep', rationale: 'Advanced/agent only — not homepage' },
  { surface: 'Swap/Liquidity/Farms/Pools', action: 'keep', rationale: 'Production core — no change' },
]

export const resolveAiAgentExperienceAudit = (): AiAgentExperienceAudit => ({
  manifest: 'manifest://melega/platform/ai-agent-experience-audit@0.1.0',
  api_version: EXPERIENCE_AUDIT_VERSION,
  phase: 'd87_experience_audit',
  as_of: EXPERIENCE_AUDIT_AS_OF,
  audit_type: 'read_only',
  branch_audited: EXPERIENCE_AUDIT_BRANCH,
  disclaimer: EXPERIENCE_AUDIT_DISCLAIMER,
  scores: { ...EXPERIENCE_AUDIT_SCORES },
  verdict: 'CONDITIONAL_D87 — strong machine layer, weak human navigation convergence',
  criticalFindings: [...CRITICAL_FINDINGS],
  surfaces: SURFACE_EXPERIENCE_AUDITS.map((surface) => ({
    ...surface,
    findings: [...surface.findings],
  })),
  journeys: ECONOMIC_JOURNEYS.map((journey) => ({
    ...journey,
    steps: journey.steps.map((step) => ({ ...step })),
    blockers: [...journey.blockers],
  })),
  homepageTiers: { ...HOMEPAGE_TIERS },
  navigationRecommendations: NAVIGATION_RECOMMENDATIONS.map((rec) => ({ ...rec })),
  surfacesToMerge: [...SURFACES_TO_MERGE],
  surfacesToRetire: [...SURFACES_TO_RETIRE],
  recommendedHomepageArchitecture: [...RECOMMENDED_HOMEPAGE_ARCHITECTURE],
  recommendedMission22: RECOMMENDED_MISSION_22,
})
