import { SubmissionValidationRule } from './submission-types'

const GLOBAL_FORBIDDEN_KEYS = [
  'signed_tx',
  'router_execute',
  'swap_execute',
  'mint_tx',
  'deploy_tx',
  'private_key',
  'auto_approve',
  'registry_write',
]

export const SUBMISSION_VALIDATION_RULES: SubmissionValidationRule[] = [
  {
    id: 'token_metadata_validation',
    category: 'token_metadata',
    description: 'Token metadata must not include deployment or mint fields.',
    requiredFieldIds: ['token_name', 'token_symbol', 'decimals', 'asset_slug'],
    forbiddenPayloadKeys: [...GLOBAL_FORBIDDEN_KEYS, 'contract_address'],
    onMissing: 'not_indexed',
    onForbidden: 'invalid',
  },
  {
    id: 'token_logo_validation',
    category: 'token_logo',
    description: 'Logo submission is URI reference only — no binary upload.',
    requiredFieldIds: ['asset_slug', 'logo_uri'],
    forbiddenPayloadKeys: [...GLOBAL_FORBIDDEN_KEYS, 'file_blob', 'base64_image'],
    onMissing: 'pending',
    onForbidden: 'invalid',
  },
  {
    id: 'website_validation',
    category: 'website',
    description: 'Website must be HTTPS URI with project binding.',
    requiredFieldIds: ['project_slug', 'website_url'],
    forbiddenPayloadKeys: GLOBAL_FORBIDDEN_KEYS,
    onMissing: 'not_indexed',
    onForbidden: 'invalid',
  },
  {
    id: 'social_links_validation',
    category: 'social_links',
    description: 'At least project_slug required; social URIs optional.',
    requiredFieldIds: ['project_slug'],
    forbiddenPayloadKeys: GLOBAL_FORBIDDEN_KEYS,
    onMissing: 'not_indexed',
    onForbidden: 'invalid',
  },
  {
    id: 'project_narrative_validation',
    category: 'project_narrative',
    description: 'Narrative requires constitutional fit disclosure.',
    requiredFieldIds: ['narrative_title', 'narrative_summary', 'constitutional_fit'],
    forbiddenPayloadKeys: [...GLOBAL_FORBIDDEN_KEYS, 'validated', 'approved'],
    onMissing: 'pending',
    onForbidden: 'invalid',
  },
  {
    id: 'whitepaper_validation',
    category: 'whitepaper',
    description: 'Whitepaper URI only — no hosted document in this build.',
    requiredFieldIds: ['project_slug', 'whitepaper_uri'],
    forbiddenPayloadKeys: [...GLOBAL_FORBIDDEN_KEYS, 'file_blob'],
    onMissing: 'not_indexed',
    onForbidden: 'invalid',
  },
  {
    id: 'audit_reference_validation',
    category: 'audit_reference',
    description: 'Audit reference is informational — not safety certification.',
    requiredFieldIds: ['asset_slug', 'audit_uri', 'auditor_name'],
    forbiddenPayloadKeys: GLOBAL_FORBIDDEN_KEYS,
    onMissing: 'pending',
    onForbidden: 'invalid',
  },
  {
    id: 'category_classification_validation',
    category: 'category_classification',
    description: 'Taxonomy ids must be from approved list when indexed.',
    requiredFieldIds: ['asset_slug', 'taxonomy_ids'],
    forbiddenPayloadKeys: GLOBAL_FORBIDDEN_KEYS,
    onMissing: 'not_indexed',
    onForbidden: 'invalid',
  },
  {
    id: 'presence_request_validation',
    category: 'economic_presence_request',
    description: 'Presence requests must not claim canonical override.',
    requiredFieldIds: ['presence_slug', 'chain_role', 'target_chain'],
    forbiddenPayloadKeys: [...GLOBAL_FORBIDDEN_KEYS, 'canonical_override', 'replace_marco'],
    onMissing: 'pending',
    onForbidden: 'invalid',
  },
  {
    id: 'launch_request_validation',
    category: 'launch_request',
    description: 'Launch requests signal intent only — no auto capability activation.',
    requiredFieldIds: ['capability_type', 'project_slug'],
    forbiddenPayloadKeys: [...GLOBAL_FORBIDDEN_KEYS, 'force_live', 'ilo_route'],
    onMissing: 'pending',
    onForbidden: 'invalid',
  },
  {
    id: 'future_ai_review_validation',
    category: 'future_ai_review',
    description: 'AI review pipeline not active — submissions blocked from auto-review.',
    requiredFieldIds: ['review_subject'],
    forbiddenPayloadKeys: [...GLOBAL_FORBIDDEN_KEYS, 'auto_review_pass'],
    onMissing: 'not_indexed',
    onForbidden: 'blocked',
  },
]

export const GLOBAL_SUBMISSION_VALIDATION_NOTES = [
  'No form persistence in this build — submissions are schema examples only.',
  'No file upload or storage handling.',
  'No automatic registry mutation on validation pass.',
  'approved review status cannot be set without human reviewer in future missions.',
]
