/**
 * Certified Project Growth Hub registry — PP013 read model.
 * ACTIVE never invented. SmartDrop/referral/airdrop remain UNAVAILABLE until live surfaces exist.
 */
import type { RegistryGrowthProgramRecord, RegistryGrowthRelationRecord } from './types'

const UPDATED = '2026-07-21T00:00:00.000Z'
const BSC = [56] as number[]

export const PROJECT_GROWTH_PROGRAMS: RegistryGrowthProgramRecord[] = [
  {
    stableKey: 'melega-dex.growth.smartdrop',
    projectSlug: 'melega-dex',
    category: 'SMARTDROP',
    type: 'CAMPAIGN',
    title: 'SmartDrop Campaigns',
    summary:
      'SmartDrop campaign product is planned (Phase 2). No dedicated SmartDrop route or live campaign registry is certified on the Project Page.',
    status: 'UNAVAILABLE',
    route: null,
    externalUrl: null,
    capabilities: ['smartdrop'],
    supportedChains: BSC,
    evidenceClaimTypes: [],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: ['ecosystem', 'participate'],
    relatedServiceStableKeys: ['melega-dex.service.smartdrop'],
    relatedUpdateStableKeys: [],
    relatedDeveloperStableKeys: [],
    machineTags: ['smartdrop', 'campaign', 'unavailable'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.referral',
    projectSlug: 'melega-dex',
    category: 'REFERRAL',
    type: 'PROGRAM',
    title: 'Referral Rewards',
    summary:
      'Referral settlement runtime is not available in this repository. No /referral surface or referral reward claims are exposed.',
    status: 'UNAVAILABLE',
    route: null,
    externalUrl: null,
    capabilities: [],
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'UNKNOWN',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    relatedDeveloperStableKeys: [],
    machineTags: ['referral', 'unavailable'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.campaigns',
    projectSlug: 'melega-dex',
    category: 'CAMPAIGN',
    type: 'PROGRAM',
    title: 'Campaign Registry',
    summary:
      'No project campaign registry entries are certified. Asset-level campaigns arrays are empty in the repository.',
    status: 'UNAVAILABLE',
    route: null,
    externalUrl: null,
    capabilities: [],
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'UNKNOWN',
    relatedSectionIds: ['updates'],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    relatedDeveloperStableKeys: [],
    machineTags: ['campaign', 'registry', 'unavailable'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.airdrop',
    projectSlug: 'melega-dex',
    category: 'AIRDROP',
    type: 'CAMPAIGN',
    title: 'Airdrop Programs',
    summary:
      'No airdrop campaign indexer or claim surface is registered for Melega DEX. Marketing copy alone is not a growth program.',
    status: 'UNAVAILABLE',
    route: null,
    externalUrl: null,
    capabilities: [],
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'UNKNOWN',
    relatedSectionIds: [],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    relatedDeveloperStableKeys: [],
    machineTags: ['airdrop', 'unavailable'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.ambassador',
    projectSlug: 'melega-dex',
    category: 'AMBASSADOR',
    type: 'PROGRAM',
    title: 'Ambassador Program',
    summary: 'No ambassador program metadata or destination is registered in the repository.',
    status: 'UNAVAILABLE',
    route: null,
    externalUrl: null,
    capabilities: [],
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'UNKNOWN',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    relatedDeveloperStableKeys: [],
    machineTags: ['ambassador', 'unavailable'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.missions',
    projectSlug: 'melega-dex',
    category: 'MISSION',
    type: 'PROGRAM',
    title: 'User Missions',
    summary: 'Repository “missions” refer to internal engineering tickets, not a user-facing mission/quest product.',
    status: 'UNAVAILABLE',
    route: null,
    externalUrl: null,
    capabilities: [],
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'UNKNOWN',
    relatedSectionIds: [],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    relatedDeveloperStableKeys: [],
    machineTags: ['missions', 'unavailable'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.launch',
    projectSlug: 'melega-dex',
    category: 'LAUNCHPAD',
    type: 'PORTAL',
    title: 'Launch / ILO',
    summary:
      'ILO route is preserved for retirement notice. Launch capability is partial; pad is not an active growth campaign.',
    status: 'PLANNED',
    route: '/ilo',
    externalUrl: null,
    capabilities: ['launch'],
    supportedChains: BSC,
    evidenceClaimTypes: [],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: ['ecosystem', 'participate'],
    relatedServiceStableKeys: ['melega-dex.service.ilo'],
    relatedUpdateStableKeys: [],
    relatedDeveloperStableKeys: [],
    machineTags: ['ilo', 'launch', 'planned'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.labs',
    projectSlug: 'melega-dex',
    category: 'ECOSYSTEM',
    type: 'PORTAL',
    title: 'Labs Narrative',
    summary: 'Labs runtime page exists; project capability remains planned. Not certified as an ACTIVE growth program.',
    status: 'PLANNED',
    route: '/runtime/labs',
    externalUrl: null,
    capabilities: ['labs'],
    supportedChains: BSC,
    evidenceClaimTypes: [],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: ['melega-dex.service.labs'],
    relatedUpdateStableKeys: [],
    relatedDeveloperStableKeys: [],
    machineTags: ['labs', 'planned'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.radar',
    projectSlug: 'melega-dex',
    category: 'ECOSYSTEM',
    type: 'PORTAL',
    title: 'Radar Visibility',
    summary:
      'Radar product route exists; registry capability is planned. Discovery surface only — not campaign execution.',
    status: 'PLANNED',
    route: '/radar',
    externalUrl: null,
    capabilities: ['radar'],
    supportedChains: BSC,
    evidenceClaimTypes: [],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: ['melega-dex.service.radar'],
    relatedUpdateStableKeys: [],
    relatedDeveloperStableKeys: [],
    machineTags: ['radar', 'visibility', 'planned'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.space',
    projectSlug: 'melega-dex',
    category: 'COMMUNITY',
    type: 'PORTAL',
    title: 'Space Community',
    summary: 'External Melega Space link from project registry. Community bind is not a live campaign engine.',
    status: 'PLANNED',
    route: null,
    externalUrl: 'https://melega.space/',
    capabilities: ['space'],
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: ['melega-dex.service.space'],
    relatedUpdateStableKeys: [],
    relatedDeveloperStableKeys: [],
    machineTags: ['space', 'community', 'planned'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.trending',
    projectSlug: 'melega-dex',
    category: 'MARKETING',
    type: 'DISCOVERY',
    title: 'Trending Discovery',
    summary:
      'Trending page exists as a discovery surface. It is not a certified PP009 ACTIVE ecosystem growth campaign.',
    status: 'PREVIEW',
    route: '/trending',
    externalUrl: null,
    capabilities: [],
    supportedChains: BSC,
    evidenceClaimTypes: [],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: ['ecosystem', 'participate'],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    relatedDeveloperStableKeys: [],
    machineTags: ['trending', 'preview'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.onboarding',
    projectSlug: 'melega-dex',
    category: 'ONBOARDING',
    type: 'TOOLING',
    title: 'Project Onboarding',
    summary:
      'Import / onboard tooling helps projects join the registry. This is onboarding tooling — not a user acquisition campaign.',
    status: 'PREVIEW',
    route: '/import-existing-token',
    externalUrl: null,
    capabilities: [],
    supportedChains: BSC,
    evidenceClaimTypes: ['PROJECT_IDENTITY'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['developer', 'ecosystem'],
    relatedServiceStableKeys: ['melega-dex.service.build-studio'],
    relatedUpdateStableKeys: ['melega-dex.canonical-project-page-identity'],
    relatedDeveloperStableKeys: ['melega-dex.dev.api.project-page'],
    machineTags: ['onboarding', 'import', 'preview'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.build-extensions',
    projectSlug: 'melega-dex',
    category: 'ECOSYSTEM',
    type: 'TOOLING',
    title: 'Build Studio Growth Extensions',
    summary:
      'Build Studio hosts growth-adjacent infrastructure suggestions. Extensions remain gated; SmartDrop is not available today.',
    status: 'PREVIEW',
    route: '/build-studio',
    externalUrl: null,
    capabilities: [],
    supportedChains: BSC,
    evidenceClaimTypes: [],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: ['ecosystem', 'developer'],
    relatedServiceStableKeys: ['melega-dex.service.build-studio'],
    relatedUpdateStableKeys: [],
    relatedDeveloperStableKeys: [],
    machineTags: ['build-studio', 'extensions', 'preview'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.liquidity-participate',
    projectSlug: 'melega-dex',
    category: 'LIQUIDITY_INCENTIVE',
    type: 'DISCOVERY',
    title: 'Liquidity Incentive Discovery',
    summary:
      'Farm and pool incentive surfaces are discovered via the Participation hub (PP006). Not registered as a separate Growth campaign engine — no emission metrics here.',
    status: 'PREVIEW',
    route: '/farms',
    externalUrl: null,
    capabilities: ['farm', 'pool'],
    supportedChains: BSC,
    evidenceClaimTypes: [],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['participate'],
    relatedServiceStableKeys: ['melega-dex.service.farms', 'melega-dex.service.pools'],
    relatedUpdateStableKeys: ['melega-dex.participation-farms-pools'],
    relatedDeveloperStableKeys: [],
    machineTags: ['liquidity', 'farms', 'pools', 'preview'],
    updatedAt: UPDATED,
  },
  {
    stableKey: 'melega-dex.growth.ai-report',
    projectSlug: 'melega-dex',
    category: 'OTHER',
    type: 'RESOURCE',
    title: 'AI Growth Report',
    summary: 'AI report capability is planned/unavailable. No live growth analytics product is certified.',
    status: 'UNAVAILABLE',
    route: null,
    externalUrl: null,
    capabilities: ['aiReport'],
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: ['ecosystem', 'developer'],
    relatedServiceStableKeys: ['melega-dex.service.ai-report'],
    relatedUpdateStableKeys: [],
    relatedDeveloperStableKeys: [],
    machineTags: ['ai', 'report', 'unavailable'],
    updatedAt: UPDATED,
  },
]

export const PROJECT_GROWTH_RELATIONS: RegistryGrowthRelationRecord[] = [
  {
    fromStableKey: 'melega-dex.growth.onboarding',
    toStableKey: 'melega-dex.growth.build-extensions',
    relationType: 'USES',
  },
  {
    fromStableKey: 'melega-dex.growth.liquidity-participate',
    toStableKey: 'melega-dex.growth.trending',
    relationType: 'COMPOSES',
  },
]

export function listGrowthProgramsForSlug(slug: string): RegistryGrowthProgramRecord[] {
  return PROJECT_GROWTH_PROGRAMS.filter((r) => r.projectSlug === slug)
}

export function listGrowthRelationsForSlug(slug: string): RegistryGrowthRelationRecord[] {
  const keys = new Set(listGrowthProgramsForSlug(slug).map((r) => r.stableKey))
  return PROJECT_GROWTH_RELATIONS.filter((r) => keys.has(r.fromStableKey) && keys.has(r.toStableKey))
}
