import {
  buildPresenceId,
  MARCO_CANONICAL_UAI,
  MELEGA_DEX_UPI,
  PRESENCE_REGISTRY_AS_OF,
  PRESENCE_REGISTRY_DISCLAIMER,
} from './presence-constants'
import { StaticPresenceRecord } from './presence-types'

const baseLinks = {
  graph: '/graph',
  query: '/query',
}

export const STATIC_PRESENCE_RECORDS: StaticPresenceRecord[] = [
  {
    slug: 'marco-bnb-canonical',
    presenceId: buildPresenceId('marco-bnb-canonical'),
    displayName: 'MARCO on BNB Chain',
    description:
      'Constitutional Canonical Economy presence. MARCO on BNB Chain is LIVE and immutable — not replaceable by Economic Presence layers.',
    projectUpi: MELEGA_DEX_UPI,
    projectSlug: 'melega-dex',
    canonicalAssetUai: MARCO_CANONICAL_UAI,
    assetSlug: 'marco',
    chainId: 56,
    chainLabel: 'BNB Chain',
    venueSource: 'Melega DEX V2',
    presenceType: 'canonical',
    status: 'LIVE',
    liquidityConfidence: 'canonical',
    executionEligibility: 'eligible',
    canonicalRelationship: 'canonical',
    isCanonical: true,
    warnings: [],
    links: {
      ...baseLinks,
      asset: '/assets/marco',
      venue: '/venues/marco-bnb-lp',
      execution: '/execution',
    },
    disclaimer: PRESENCE_REGISTRY_DISCLAIMER,
    dataSource: 'presence-registry-static',
    asOf: PRESENCE_REGISTRY_AS_OF,
    mvpStatic: true,
  },
  {
    slug: 'marco-ethereum-presence',
    presenceId: buildPresenceId('marco-ethereum-presence'),
    displayName: 'MARCO on Ethereum',
    description:
      'Observed Economic Presence on Ethereum. MARCO deployment indexed — not the Canonical Economy.',
    projectUpi: MELEGA_DEX_UPI,
    projectSlug: 'melega-dex',
    canonicalAssetUai: MARCO_CANONICAL_UAI,
    assetSlug: 'marco-ethereum',
    chainId: 1,
    chainLabel: 'Ethereum',
    venueSource: 'Legacy token list / bridge surface',
    presenceType: 'economic_presence',
    status: 'OBSERVED',
    liquidityConfidence: 'low',
    executionEligibility: 'conditional',
    canonicalRelationship: 'economic_presence_only',
    isCanonical: false,
    warnings: [
      'NOT CANONICAL — Economic Presence only',
      'Low liquidity confidence — no indexed depth figures in this read model',
      'Does not replace MARCO on BNB Chain',
    ],
    links: {
      ...baseLinks,
      asset: '/assets/marco-ethereum',
      execution: '/execution',
    },
    disclaimer: PRESENCE_REGISTRY_DISCLAIMER,
    dataSource: 'presence-registry-static',
    asOf: PRESENCE_REGISTRY_AS_OF,
    mvpStatic: true,
  },
  {
    slug: 'marco-polygon-presence',
    presenceId: buildPresenceId('marco-polygon-presence'),
    displayName: 'MARCO on Polygon',
    description:
      'Observed Economic Presence on Polygon. Presence layer only — not Canonical Economy.',
    projectUpi: MELEGA_DEX_UPI,
    projectSlug: 'melega-dex',
    canonicalAssetUai: MARCO_CANONICAL_UAI,
    assetSlug: 'marco-polygon',
    chainId: 137,
    chainLabel: 'Polygon',
    venueSource: 'Legacy token list / bridge surface',
    presenceType: 'economic_presence',
    status: 'OBSERVED',
    liquidityConfidence: 'low',
    executionEligibility: 'conditional',
    canonicalRelationship: 'economic_presence_only',
    isCanonical: false,
    warnings: [
      'NOT CANONICAL — Economic Presence only',
      'Low liquidity confidence — no fake liquidity numbers',
      'Does not replace MARCO on BNB Chain',
    ],
    links: {
      ...baseLinks,
      asset: '/assets/marco-polygon',
      execution: '/execution',
    },
    disclaimer: PRESENCE_REGISTRY_DISCLAIMER,
    dataSource: 'presence-registry-static',
    asOf: PRESENCE_REGISTRY_AS_OF,
    mvpStatic: true,
  },
  {
    slug: 'marco-base-presence',
    presenceId: buildPresenceId('marco-base-presence'),
    displayName: 'MARCO on Base',
    description:
      'Observed Economic Presence on Base. Presence layer only — not Canonical Economy.',
    projectUpi: MELEGA_DEX_UPI,
    projectSlug: 'melega-dex',
    canonicalAssetUai: MARCO_CANONICAL_UAI,
    assetSlug: 'marco-base',
    chainId: 8453,
    chainLabel: 'Base',
    venueSource: 'Legacy token list / bridge surface',
    presenceType: 'economic_presence',
    status: 'OBSERVED',
    liquidityConfidence: 'low',
    executionEligibility: 'conditional',
    canonicalRelationship: 'economic_presence_only',
    isCanonical: false,
    warnings: [
      'NOT CANONICAL — Economic Presence only',
      'Low liquidity confidence — not indexed as canonical MARCO surface',
      'Does not replace MARCO on BNB Chain',
    ],
    links: {
      ...baseLinks,
      asset: '/assets/marco-base',
      execution: '/execution',
    },
    disclaimer: PRESENCE_REGISTRY_DISCLAIMER,
    dataSource: 'presence-registry-static',
    asOf: PRESENCE_REGISTRY_AS_OF,
    mvpStatic: true,
  },
  {
    slug: 'solana-melega-planned',
    presenceId: buildPresenceId('solana-melega-planned'),
    displayName: 'Solana Melega Surface',
    description:
      'Planned Economic Presence on Solana. Not indexed, not canonical, no on-chain presence in this registry build.',
    projectUpi: MELEGA_DEX_UPI,
    projectSlug: 'melega-dex',
    canonicalAssetUai: MARCO_CANONICAL_UAI,
    chainLabel: 'Solana',
    venueSource: 'Planned Melega surface (not indexed)',
    presenceType: 'planned_surface',
    status: 'PLANNED',
    liquidityConfidence: 'planned',
    executionEligibility: 'not_eligible',
    canonicalRelationship: 'planned_presence',
    isCanonical: false,
    warnings: [
      'NOT CANONICAL — planned presence only',
      'Not indexed on-chain in this build',
      'Never replaces MARCO on BNB Chain as canonical asset',
    ],
    links: {
      ...baseLinks,
    },
    disclaimer: PRESENCE_REGISTRY_DISCLAIMER,
    dataSource: 'presence-registry-static',
    asOf: PRESENCE_REGISTRY_AS_OF,
    mvpStatic: true,
  },
]
