import { premiumStudioColors, premiumStudioLayout } from 'design-system/melega/tokens/premiumStudio'
import { studioConstitutionLayout } from 'design-system/melega/tokens/studioConstitution'
import { ds001Colors, ds001Shadows, ds001Spacing } from 'design-system/melega/tokens/ds001'

/** Pools Studio — R705 Step 1 layout foundation. */
export const poolsStudioLayout = {
  ...premiumStudioLayout,
  ...studioConstitutionLayout,
  containerMax: '1440px',
  contentPaddingMobile: '18px',
  gapHeaderKpi: ds001Spacing[32],
  gapKpiHero: '32px',
  gapHeroExplorer: '48px',
  gapExplorerGrid: '24px',
  explorerMaxWidth: '940px',
  gapGridBuilder: '40px',
  gapBuilderBottom: '24px',
  mainColumnWidth: '820px',
  pageGridGap: '24px',
  cardGap: '18px',
  poolCardRowGap: '22px',
  kpiGap: '16px',
  kpiPadding: '22px 22px 20px 22px',
  kpiRadius: '18px',
  kpiMobileWidth: '170px',
  kpiMobileHeight: '104px',
  kpiMobileGap: '12px',
  kpiDeltaGap: '8px',
  headerHeight: '112px',
  headerControlsTop: '18px',
  headerSubtitleTop: '76px',
  headerCreateBtnWidth: '180px',
  headerCreateBtnHeight: '52px',
  headerCreateBtnRadius: '14px',
  livePillWidth: '142px',
  livePillHeight: '34px',
  livePillGap: '16px',
  featuredHeight: '320px',
  featuredMinHeight: '260px',
  featuredMaxHeight: '320px',
  featuredExpandedHeight: '320px',
  featuredStakeBtnWidth: '180px',
  featuredAnalyzeBtnWidth: '180px',
  featuredBtnHeight: '48px',
  sidebarWidth: '340px',
  sidebarCardGap: '16px',
  sidebarCardPadding: '22px',
  sidebarAdvisorHeight: '220px',
  sidebarHealthHeight: '160px',
  sidebarRewardHeight: '220px',
  toolbarHeight: '36px',
  toolbarChipsGap: '14px',
  tabHeight: '36px',
  viewSwitchWidth: '96px',
  viewSwitchHeight: '34px',
  sortSelectWidth: '188px',
  filterBtnWidth: '92px',
  filterPillHeight: '30px',
  filterChipRowHeight: '30px',
  filterGap: '8px',
  poolCardHeight: '258px',
  poolCardExpandedHeight: '390px',
  poolCardWidth: '312px',
  poolCardBtnHeight: '42px',
  poolCardBtnWidth: '132px',
  poolCardBtnGap: '10px',
  poolCardBtnRadius: '12px',
  createPoolBtnWidth: '180px',
  createPoolBtnHeight: '44px',
  createPoolFieldHeight: '44px',
  emptyGridHeight: '136px',
  bottomPanelHeight: '160px',
  hoverTransition: '180ms',
  drawerTransition: '220ms',
  mobileBottomPad: '180px',
  mobileContentPaddingTop: '16px',
  mobileTitleSize: '44px',
  mobileLivePillWidth: '130px',
  mobileLivePillHeight: '32px',
  mobileCreateBtnWidth: '160px',
  mobileCreateBtnHeight: '46px',
  donutDiameter: 128,
  donutDiameterMobile: 128,
} as const

/** R721 — Featured Hero enterprise polish tokens. */
export const poolsFeaturedHero = {
  height: '300px',
  padding: '30px 34px 28px',
  aprSize: '64px',
  aprLineHeight: '64px',
  aprColor: '#19F08A',
  gapAprName: '18px',
  gapNameBadges: '10px',
  gapBadgesKpi: '18px',
  gapKpiButtons: '22px',
  badgeGap: '10px',
  kpiWidth: '118px',
  kpiHeight: '56px',
  donutDiameter: 88,
  rewardRowGap: '22px',
  healthBarWidth: '96px',
  healthBarHeight: '6px',
} as const

export const poolsStudioColors = {
  ...premiumStudioColors,
  canvas: ds001Colors.background,
  surfacePrimary: ds001Colors.surface,
  panel: ds001Colors.surface,
  card: ds001Colors.surface,
  cardElevated: ds001Colors.cardHoverBackground,
  cardHover: ds001Colors.surface,
  gold: ds001Colors.primaryGold,
  goldBright: ds001Colors.hoverGold,
  explorerGold: ds001Colors.primaryGold,
  /** Gradients retired for fills — solid DS001.1 gold retained for compatibility keys. */
  goldGradient: ds001Colors.primaryGold,
  goldSoft: 'rgba(244, 196, 48, 0.12)',
  goldButtonGlow: ds001Shadows.default,
  aprGreen: ds001Colors.success,
  green: ds001Colors.success,
  greenSoft: 'rgba(34, 197, 94, 0.06)',
  red: ds001Colors.danger,
  text: ds001Colors.primaryText,
  secondary: ds001Colors.secondaryText,
  subtitle: ds001Colors.secondaryText,
  muted: ds001Colors.muted,
  mutedSecondary: ds001Colors.muted,
  border: ds001Colors.border,
  borderGold: ds001Colors.primaryGold,
  borderGoldFeatured: 'rgba(244, 196, 48, 0.55)',
  borderGoldHover: 'rgba(244, 196, 48, 0.65)',
  rowBorder: ds001Colors.border,
  goldBorder: ds001Colors.primaryGold,
  previewBadgeBg: 'rgba(34, 197, 94, 0.06)',
  cardBorderHover: ds001Colors.cardHoverBorder,
  chipBorder: ds001Colors.border,
  explorerEmptyBorder: ds001Colors.divider,
  tabInactive: ds001Colors.muted,
  explorerEmptyMain: ds001Colors.secondaryText,
  explorerEmptySecondary: ds001Colors.muted,
  elevationHover: ds001Shadows.hover,
} as const

export const POOLS_STUDIO_LIVE_LABEL = 'Live Runtime'
export const POOLS_STUDIO_PREVIEW_LABEL = 'PREVIEW LAYOUT'
export const POOLS_ACTIVITY_PREVIEW_LABEL = 'Indexed Preview'
