/** Farms Studio layout constants — R005-D data restore. */
export const farmsStudioLayout = {
  contentMax: '1180px',
  contentPaddingX: '24px',
  contentPaddingTop: '28px',
  contentPaddingBottom: '48px',
  sectionGap: '20px',
  pageGridColumns: 3,
  pageGridGap: '14px',
  kpiGap: '12px',
  kpiHeight: '96px',
  sparklineW: 48,
  sparklineH: 18,
  kpiDeltaGap: '16px',
  kpiSparkGap: '8px',
  featuredHeight: '270px',
  featuredMetricColWidth: '120px',
  filterHeight: '44px',
  filterMarginTop: '16px',
  gridGap: '20px',
  gridMarginTop: '16px',
  farmCardHeight: '320px',
  farmCardHeightExpanded: 'auto',
  farmCardFooterHeight: 'auto',
  farmCardPadding: '16px',
  farmCardBtnHeight: '44px',
  farmCardBtnWidth: 'auto',
  farmCardAnalyzeWidth: 'auto',
  farmCardBtnGap: '8px',
  farmCardAprGap: '14px',
  farmCardMetricsFooterGap: '16px',
  farmCardMetricRowGap: '12px',
  farmCardMetricColGap: '16px',
  featuredGridAdjust: '12px',
  activityHeight: '250px',
  activityMarginTop: '18px',
  activityRowHeight: '42px',
  activityCellPadding: '18px',
  mobileBottomPad: 'calc(96px + env(safe-area-inset-bottom, 0px))',
} as const

export const farmsStudioColors = {
  canvas: '#050505',
  panel: '#101010',
  panelAlt: '#121212',
  gold: '#D4AF37',
  goldBright: '#F4C542',
  green: '#00E676',
  red: '#FF4D4D',
  purple: '#A78BFA',
  muted: '#8A8A8A',
  subtitle: '#A8A8A8',
  text: '#FFFFFF',
  border: 'rgba(255,255,255,0.08)',
  rowBorder: 'rgba(255,255,255,0.05)',
  goldBorder: 'rgba(212,175,55,0.45)',
  goldBg: 'rgba(212,175,55,0.14)',
  previewBadgeBg: 'rgba(212,175,55,0.1)',
} as const

export const FARMS_STUDIO_PREVIEW_LABEL = 'LIVE RUNTIME'
export const FARMS_ACTIVITY_PREVIEW_LABEL = 'LIVE'
