import { LbDocsPage } from 'views/LiquidityStudio/liquidityBuilding/LbDocsPage'
import { CHAIN_IDS } from 'utils/wagmi'

const Page = () => (
  <LbDocsPage
    path="/docs/liquidity-builder/fees"
    title="Fees"
    lead="A protocol fee from Liquidity Builder activity supports the Melega treasury path."
    sections={[
      {
        title: 'Protocol fee',
        body: (
          <p>
            <strong>10%</strong> protocol fee generated by Liquidity Builder activity (success / program fee path as
            configured in the product).
          </p>
        ),
      },
      {
        title: 'Fee flow',
        body: (
          <>
            <p>Fees move along this path:</p>
            <p>
              Program
              <br />↓
              <br />
              FeeSink
              <br />↓
              <br />
              FeeReceiver
              <br />↓
              <br />
              MELEGA TREASURY
            </p>
            <p>
              There is <strong>no Treasury Runtime</strong> in this product path — fees follow FeeSink → FeeReceiver →
              MELEGA TREASURY.
            </p>
          </>
        ),
      },
    ]}
  />
)

Page.chains = CHAIN_IDS
export default Page
