/** Radar Console layout — R008 operational intelligence architecture. */
export const radarStudioLayout = {
  contentMax: '1180px',
  contentPaddingTop: '28px',
  contentPaddingX: '24px',
  contentPaddingBottom: '36px',
  sectionGap: '16px',
  colLeft: '340px',
  colCenter: '520px',
  colRight: '320px',
  columnGap: '16px',
  cardRadius: '20px',
  kpiGap: '16px',
  kpiHeight: '138px',
  kpiRadius: '18px',
  kpiPadding: '20px',
  eventStreamHeight: '52px',
  filterHeight: '42px',
  filterRadius: '21px',
  filterGap: '10px',
  eventCardWidth: '430px',
  eventCardHeight: '220px',
  eventCardGap: '16px',
  eventBtnHeight: '40px',
  eventBtnGap: '10px',
  widgetGap: '16px',
  heatmapHeight: '240px',
  gaugeSize: '120px',
  stackBreakpoint: '1180px',
  mobileBottomPad: '88px',
} as const

export const radarStudioColors = {
  canvas: '#0B0B0B',
  panel: '#131313',
  panelAlt: '#111111',
  border: '#262626',
  green: '#12F27E',
  gold: '#D9B443',
  yellow: '#E9C84D',
  orange: '#F2A93B',
  red: '#FF4D4F',
  white: '#FFFFFF',
  grey: '#9A9A9A',
  subtitle: '#A8A8A8',
  secondary: '#9C9C9C',
  hoverBorder: '#D9B443',
  shadow: '0 12px 30px rgba(0,0,0,0.35)',
} as const

export const RADAR_FONT_DISPLAY = 'Orbitron, sans-serif'
export const RADAR_FONT_BODY = '"Inter", -apple-system, BlinkMacSystemFont, sans-serif'
