/** R112 canonical Radar Studio tokens — do not deviate. */
export const radarStudioLayout = {
  contentMax: '1180px',
  contentPaddingX: '32px',
  contentPaddingTop: '16px',
  contentPaddingBottom: '48px',
  sectionGap: '20px',
  cardGap: '20px',
  cardRadius: '20px',
  featuredPadding: '28px',
  featuredMetricsBtnGap: '20px',
  opsCardHeight: '160px',
  opsCardHeightMobile: '132px',
  featuredHeight: '420px',
  featuredSplitLeft: '70%',
  featuredSplitRight: '30%',
  discoveryCardHeight: '340px',
  discoverySplitLeft: '65%',
  discoverySplitRight: '35%',
  advisorRowHeight: '52px',
  advisorRowGap: '10px',
  timelineHeight: '320px',
  timelineRowHeight: '68px',
  timelineDotSize: '12px',
  signalGridGap: '10px',
  actionGroupGap: '12px',
  actionGroupRadius: '12px',
  actionGroupPadding: '12px',
  metricsSummaryGap: '8px',
  btnRadius: '12px',
  machineCollapsedHeight: '72px',
  filterPillHeight: '44px',
  btnHeight: '48px',
  featuredBtnGap: '12px',
  headerPrimaryW: '220px',
  headerPrimaryH: '48px',
  mobileBottomPad: 'calc(96px + env(safe-area-inset-bottom, 0px))',
  mobileBreakpoint: '390px',
  stackBreakpoint: '1024px',
  confidenceBarW: '120px',
  confidenceBarH: '6px',
} as const

export const radarStudioColors = {
  canvas: '#050505',
  card: '#141414',
  cardBorder: '#2A2A2A',
  cardBorderHover: '#D4AF37',
  gold: '#D4AF37',
  green: '#1BE77A',
  red: '#FF4D4F',
  orange: '#FF9F43',
  muted: '#8F8F8F',
  secondary: '#A3A3A3',
  subtitle: '#A3A3A3',
  summary: '#D8D8D8',
  text: '#FFFFFF',
  divider: '#262626',
  goldBg: 'rgba(212,175,55,0.14)',
  heatInactive: '#222222',
} as const

export const RADAR_FONT_DISPLAY = "'Orbitron', sans-serif"
export const RADAR_FONT_BODY = "'Inter', sans-serif"

export const radarStudioType = {
  pageTitle: '52px',
  pageTitleMobile: '42px',
  pageSubtitle: '16px',
  pageSubtitleMax: '560px',
  opsTitle: '18px',
  opsDesc: '14px',
  opsIcon: '44px',
  opsIconMobile: '34px',
  featuredName: '42px',
  scoreLarge: '58px',
  scoreLargeMobile: '46px',
  scoreRingSize: '132px',
  scoreRingSizeMobile: '104px',
  timelineTitle: '15px',
  timelineSub: '13px',
} as const
