/**
 * Certified AI Agent Interface registry — PP014.
 * Navigation / discovery only. No execution descriptors.
 */
import type {
  RegistryMachineActionRecord,
  RegistryMachineCapabilityRecord,
  RegistryMachineRelationRecord,
  RegistryMachineResourceRecord,
} from './types'

function capability(
  key: string,
  capability: RegistryMachineCapabilityRecord['capability'],
  title: string,
  summary: string,
  relatedSectionIds: string[],
  relatedEndpointPaths: string[],
  tags: string[],
): RegistryMachineCapabilityRecord {
  return {
    stableKey: key,
    projectSlug: 'melega-dex',
    capability,
    title,
    summary,
    availability: 'AVAILABLE',
    relatedSectionIds,
    relatedEndpointPaths,
    machineTags: tags,
  }
}

function action(
  key: string,
  capability: RegistryMachineActionRecord['capability'],
  kind: RegistryMachineActionRecord['kind'],
  title: string,
  summary: string,
  route: string,
  requiredContext: string[],
  chainRequired: number | null,
  status: RegistryMachineActionRecord['status'] = 'ACTIVE',
  limitations: string[] = ['Navigation/discovery only — no transaction payload.'],
): RegistryMachineActionRecord {
  return {
    stableKey: key,
    projectSlug: 'melega-dex',
    capability,
    kind,
    title,
    summary,
    route,
    requiredContext,
    walletRequired: false,
    chainRequired,
    availability: 'AVAILABLE',
    status,
    limitations,
    machineTags: [kind.toLowerCase(), capability.toLowerCase()],
  }
}

export const PROJECT_MACHINE_CAPABILITIES: RegistryMachineCapabilityRecord[] = [
  capability(
    'melega-dex.cap.view-project',
    'VIEW_PROJECT',
    'View Project',
    'Read the canonical Project Page document and identity shell.',
    ['overview'],
    ['/api/public/projects/melega-dex/'],
    ['view', 'project'],
  ),
  capability(
    'melega-dex.cap.view-evidence',
    'VIEW_EVIDENCE',
    'View Evidence',
    'Read the public evidence pack (PP002).',
    ['trust'],
    ['/api/public/projects/melega-dex/evidence/'],
    ['view', 'evidence'],
  ),
  capability(
    'melega-dex.cap.view-readiness',
    'VIEW_READINESS',
    'View Readiness',
    'Read readiness and trust snapshot documents (PP003).',
    ['trust'],
    ['/api/public/projects/melega-dex/readiness/'],
    ['view', 'readiness'],
  ),
  capability(
    'melega-dex.cap.view-trust',
    'VIEW_TRUST',
    'View Trust',
    'Discover Trust / Evidence UI section and readiness state.',
    ['trust'],
    ['/api/public/projects/melega-dex/readiness/'],
    ['view', 'trust'],
  ),
  {
    ...capability(
      'melega-dex.cap.view-wallet',
      'VIEW_WALLET_RELATIONSHIP',
      'View Wallet Relationship',
      'Wallet relationship is a client contextual surface (PP004). Not a public agent write capability.',
      [],
      [],
      ['view', 'wallet'],
    ),
    availability: 'NOT_APPLICABLE',
  },
  capability(
    'melega-dex.cap.view-markets',
    'VIEW_MARKETS',
    'View Markets',
    'Read markets orchestration document (PP005).',
    ['participate'],
    ['/api/public/projects/melega-dex/markets/'],
    ['view', 'markets'],
  ),
  capability(
    'melega-dex.cap.swap',
    'SWAP',
    'Swap Navigation',
    'Navigate to the trade surface. Does not execute swaps or return quotes.',
    ['participate'],
    ['/api/public/projects/melega-dex/markets/'],
    ['navigate', 'swap'],
  ),
  capability(
    'melega-dex.cap.view-participation',
    'VIEW_PARTICIPATION',
    'View Participation',
    'Read farms/pools participation discovery document (PP006).',
    ['participate'],
    ['/api/public/projects/melega-dex/participation/'],
    ['view', 'participation'],
  ),
  capability(
    'melega-dex.cap.add-liquidity',
    'ADD_LIQUIDITY',
    'Add Liquidity Navigation',
    'Navigate to Liquidity Studio. Does not submit liquidity transactions.',
    ['participate'],
    ['/api/public/projects/melega-dex/participation/'],
    ['navigate', 'liquidity'],
  ),
  capability(
    'melega-dex.cap.open-farm',
    'OPEN_FARM',
    'Open Farms Navigation',
    'Navigate to Farms discovery. Does not stake or harvest.',
    ['participate'],
    ['/api/public/projects/melega-dex/participation/'],
    ['navigate', 'farms'],
  ),
  capability(
    'melega-dex.cap.open-pool',
    'OPEN_POOL',
    'Open Pools Navigation',
    'Navigate to Pools discovery. Does not deposit or claim.',
    ['participate'],
    ['/api/public/projects/melega-dex/participation/'],
    ['navigate', 'pools'],
  ),
  capability(
    'melega-dex.cap.open-lb',
    'OPEN_LIQUIDITY_BUILDING',
    'Open Liquidity Building',
    'Navigate to Liquidity Building discovery (PP007). Activation may be blocked without inventing readiness.',
    ['participate'],
    ['/api/public/projects/melega-dex/liquidity-building/'],
    ['navigate', 'liquidity-building'],
  ),
  capability(
    'melega-dex.cap.view-updates',
    'VIEW_UPDATES',
    'View Updates',
    'Read verified updates timeline (PP008).',
    ['updates'],
    ['/api/public/projects/melega-dex/updates/'],
    ['view', 'updates'],
  ),
  capability(
    'melega-dex.cap.view-ecosystem',
    'VIEW_ECOSYSTEM',
    'View Ecosystem',
    'Read ecosystem utilities graph (PP009).',
    ['ecosystem'],
    ['/api/public/projects/melega-dex/ecosystem/'],
    ['view', 'ecosystem'],
  ),
  capability(
    'melega-dex.cap.view-developer',
    'VIEW_DEVELOPER',
    'View Developer Hub',
    'Read developer & documentation hub (PP010).',
    ['developer'],
    ['/api/public/projects/melega-dex/developer/'],
    ['view', 'developer'],
  ),
  capability(
    'melega-dex.cap.view-governance',
    'VIEW_GOVERNANCE',
    'View Governance Transparency',
    'Read governance/treasury disclosure (PP011). No voting or treasury control.',
    ['governance'],
    ['/api/public/projects/melega-dex/governance/'],
    ['view', 'governance'],
  ),
  capability(
    'melega-dex.cap.view-growth',
    'VIEW_GROWTH',
    'View Growth Hub',
    'Read growth program discovery (PP013). No campaign execution.',
    ['growth'],
    ['/api/public/projects/melega-dex/growth/'],
    ['view', 'growth'],
  ),
  capability(
    'melega-dex.cap.view-control-center',
    'VIEW_CONTROL_CENTER',
    'View Control Center Status',
    'Read public claim/verification summary (PP012). Private mutation APIs are not exposed to agents.',
    [],
    ['/api/public/projects/melega-dex/control-center/'],
    ['view', 'control-center'],
  ),
  capability(
    'melega-dex.cap.view-machine',
    'VIEW_MACHINE',
    'View Machine Interface',
    'Read this machine interface document (PP014).',
    ['machine'],
    ['/api/public/projects/melega-dex/machine/'],
    ['view', 'machine'],
  ),
]

export const PROJECT_MACHINE_ACTIONS: RegistryMachineActionRecord[] = [
  action(
    'melega-dex.act.navigate-project',
    'VIEW_PROJECT',
    'NAVIGATE',
    'Open Project Page',
    'Open the human Project Page for melega-dex.',
    '/project-hq/melega-dex',
    ['slug'],
    null,
  ),
  action(
    'melega-dex.act.fetch-project',
    'VIEW_PROJECT',
    'FETCH',
    'Fetch Project Document',
    'GET canonical project JSON (melega.project-page.v1).',
    '/api/public/projects/melega-dex/',
    ['slug'],
    null,
  ),
  action(
    'melega-dex.act.fetch-evidence',
    'VIEW_EVIDENCE',
    'FETCH',
    'Fetch Evidence Pack',
    'GET public evidence document.',
    '/api/public/projects/melega-dex/evidence/',
    ['slug'],
    null,
  ),
  action(
    'melega-dex.act.fetch-readiness',
    'VIEW_READINESS',
    'FETCH',
    'Fetch Readiness',
    'GET readiness / trust snapshot document.',
    '/api/public/projects/melega-dex/readiness/',
    ['slug'],
    null,
  ),
  action(
    'melega-dex.act.fetch-markets',
    'VIEW_MARKETS',
    'FETCH',
    'Fetch Markets',
    'GET markets orchestration document.',
    '/api/public/projects/melega-dex/markets/',
    ['slug'],
    null,
  ),
  action(
    'melega-dex.act.navigate-swap',
    'SWAP',
    'NAVIGATE',
    'Open Swap',
    'Navigate to trade surface. No quote or swap execution.',
    '/trade',
    ['optionalTokenContext'],
    56,
  ),
  action(
    'melega-dex.act.fetch-participation',
    'VIEW_PARTICIPATION',
    'FETCH',
    'Fetch Participation',
    'GET participation discovery document.',
    '/api/public/projects/melega-dex/participation/',
    ['slug'],
    null,
  ),
  action(
    'melega-dex.act.navigate-liquidity',
    'ADD_LIQUIDITY',
    'NAVIGATE',
    'Open Liquidity Studio',
    'Navigate to Liquidity Studio. No deposit transaction.',
    '/liquidity-studio',
    ['optionalPairContext'],
    56,
  ),
  action(
    'melega-dex.act.navigate-farms',
    'OPEN_FARM',
    'NAVIGATE',
    'Open Farms',
    'Navigate to Farms. No stake/harvest.',
    '/farms',
    [],
    56,
  ),
  action(
    'melega-dex.act.navigate-pools',
    'OPEN_POOL',
    'NAVIGATE',
    'Open Pools',
    'Navigate to Pools. No deposit/claim.',
    '/pools',
    [],
    56,
  ),
  action(
    'melega-dex.act.navigate-lb',
    'OPEN_LIQUIDITY_BUILDING',
    'NAVIGATE',
    'Open Liquidity Building',
    'Navigate to Liquidity Building view. Activation may be blocked.',
    '/liquidity-studio?view=building',
    ['slug'],
    56,
    'ACTIVE',
    [
      'Navigation only — no program activation payload.',
      'Activation readiness is reported by the Liquidity Building document, not invented here.',
    ],
  ),
  action(
    'melega-dex.act.fetch-updates',
    'VIEW_UPDATES',
    'FETCH',
    'Fetch Updates',
    'GET verified updates timeline.',
    '/api/public/projects/melega-dex/updates/',
    ['slug'],
    null,
  ),
  action(
    'melega-dex.act.fetch-ecosystem',
    'VIEW_ECOSYSTEM',
    'FETCH',
    'Fetch Ecosystem',
    'GET ecosystem utilities graph.',
    '/api/public/projects/melega-dex/ecosystem/',
    ['slug'],
    null,
  ),
  action(
    'melega-dex.act.fetch-developer',
    'VIEW_DEVELOPER',
    'FETCH',
    'Fetch Developer Hub',
    'GET developer resources document.',
    '/api/public/projects/melega-dex/developer/',
    ['slug'],
    null,
  ),
  action(
    'melega-dex.act.fetch-governance',
    'VIEW_GOVERNANCE',
    'FETCH',
    'Fetch Governance',
    'GET governance/treasury transparency document.',
    '/api/public/projects/melega-dex/governance/',
    ['slug'],
    null,
  ),
  action(
    'melega-dex.act.fetch-growth',
    'VIEW_GROWTH',
    'FETCH',
    'Fetch Growth Hub',
    'GET growth programs document.',
    '/api/public/projects/melega-dex/growth/',
    ['slug'],
    null,
  ),
  action(
    'melega-dex.act.fetch-control-center',
    'VIEW_CONTROL_CENTER',
    'FETCH',
    'Fetch Control Center Public Summary',
    'GET public claimState/ownerVerification only. No private mutations.',
    '/api/public/projects/melega-dex/control-center/',
    ['slug'],
    null,
  ),
  action(
    'melega-dex.act.fetch-machine',
    'VIEW_MACHINE',
    'FETCH',
    'Fetch Machine Interface',
    'GET this machine interface document.',
    '/api/public/projects/melega-dex/machine/',
    ['slug'],
    null,
  ),
  action(
    'melega-dex.act.discover-well-known',
    'VIEW_MACHINE',
    'DISCOVER',
    'Open Agent Discovery',
    'Open well-known project discovery pointer.',
    '/.well-known/melega-dex-discovery.json',
    [],
    null,
  ),
  action(
    'melega-dex.act.discover-machine',
    'VIEW_MACHINE',
    'DISCOVER',
    'Open Machine Well-Known',
    'Open well-known machine interface pointer.',
    '/.well-known/melega-dex-machine.json',
    [],
    null,
  ),
  action(
    'melega-dex.act.open-manifest',
    'VIEW_PROJECT',
    'DISCOVER',
    'Open Project Manifest',
    'Open static machine-readable project registry JSON.',
    '/registry/projects/melega-dex.json',
    [],
    null,
  ),
]

export const PROJECT_MACHINE_RESOURCES: RegistryMachineResourceRecord[] = [
  {
    stableKey: 'melega-dex.mres.machine-api',
    projectSlug: 'melega-dex',
    kind: 'ENDPOINT',
    title: 'Machine API',
    summary: 'Canonical machine interface endpoint for AI agents.',
    route: '/api/public/projects/melega-dex/machine/',
    schemaVersion: 'melega.project-machine.v1',
    availability: 'AVAILABLE',
    machineTags: ['endpoint', 'machine'],
  },
  {
    stableKey: 'melega-dex.mres.well-known-machine',
    projectSlug: 'melega-dex',
    kind: 'WELL_KNOWN',
    title: 'Well-Known Machine Pointer',
    summary: 'Static discovery pointer for the machine interface.',
    route: '/.well-known/melega-dex-machine.json',
    schemaVersion: null,
    availability: 'AVAILABLE',
    machineTags: ['well-known', 'discovery'],
  },
  {
    stableKey: 'melega-dex.mres.well-known-discovery',
    projectSlug: 'melega-dex',
    kind: 'WELL_KNOWN',
    title: 'Well-Known Project Discovery',
    summary: 'Existing agent discovery pointer (project registry).',
    route: '/.well-known/melega-dex-discovery.json',
    schemaVersion: null,
    availability: 'AVAILABLE',
    machineTags: ['well-known', 'discovery'],
  },
  {
    stableKey: 'melega-dex.mres.schema-project',
    projectSlug: 'melega-dex',
    kind: 'SCHEMA',
    title: 'Project Page Schema',
    summary: 'melega.project-page.v1',
    route: '/api/public/projects/melega-dex/',
    schemaVersion: 'melega.project-page.v1',
    availability: 'AVAILABLE',
    machineTags: ['schema'],
  },
  {
    stableKey: 'melega-dex.mres.schema-machine',
    projectSlug: 'melega-dex',
    kind: 'SCHEMA',
    title: 'Machine Interface Schema',
    summary: 'melega.project-machine.v1',
    route: '/api/public/projects/melega-dex/machine/',
    schemaVersion: 'melega.project-machine.v1',
    availability: 'AVAILABLE',
    machineTags: ['schema', 'machine'],
  },
  {
    stableKey: 'melega-dex.mres.section-machine',
    projectSlug: 'melega-dex',
    kind: 'SECTION',
    title: 'Machine Interface Section',
    summary: 'Human-readable Machine Interface section on the Project Page.',
    route: '/project-hq/melega-dex#machine',
    schemaVersion: null,
    availability: 'AVAILABLE',
    machineTags: ['section', 'ui'],
  },
  {
    stableKey: 'melega-dex.mres.openapi',
    projectSlug: 'melega-dex',
    kind: 'DOCUMENTATION',
    title: 'OpenAPI',
    summary: 'Published OpenAPI is not available in the repository.',
    route: null,
    schemaVersion: null,
    availability: 'UNAVAILABLE',
    machineTags: ['openapi', 'unavailable'],
  },
  {
    stableKey: 'melega-dex.mres.mcp',
    projectSlug: 'melega-dex',
    kind: 'DOCUMENTATION',
    title: 'MCP',
    summary: 'MCP server publication is not available in the repository.',
    route: null,
    schemaVersion: null,
    availability: 'UNAVAILABLE',
    machineTags: ['mcp', 'unavailable'],
  },
]

export const PROJECT_MACHINE_RELATIONS: RegistryMachineRelationRecord[] = [
  {
    fromStableKey: 'melega-dex.act.navigate-swap',
    toStableKey: 'melega-dex.cap.swap',
    relationType: 'USES_CAPABILITY',
  },
  {
    fromStableKey: 'melega-dex.act.fetch-machine',
    toStableKey: 'melega-dex.mres.machine-api',
    relationType: 'LINKS_ENDPOINT',
  },
  {
    fromStableKey: 'melega-dex.mres.machine-api',
    toStableKey: 'melega-dex.mres.schema-machine',
    relationType: 'LINKS_SCHEMA',
  },
  {
    fromStableKey: 'melega-dex.cap.view-machine',
    toStableKey: 'melega-dex.mres.machine-api',
    relationType: 'EXPOSES',
  },
]

export function listMachineCapabilitiesForSlug(slug: string): RegistryMachineCapabilityRecord[] {
  return PROJECT_MACHINE_CAPABILITIES.filter((r) => r.projectSlug === slug)
}

export function listMachineActionsForSlug(slug: string): RegistryMachineActionRecord[] {
  return PROJECT_MACHINE_ACTIONS.filter((r) => r.projectSlug === slug)
}

export function listMachineResourcesForSlug(slug: string): RegistryMachineResourceRecord[] {
  return PROJECT_MACHINE_RESOURCES.filter((r) => r.projectSlug === slug)
}

export function listMachineRelationsForSlug(slug: string): RegistryMachineRelationRecord[] {
  const keys = new Set([
    ...listMachineCapabilitiesForSlug(slug).map((r) => r.stableKey),
    ...listMachineActionsForSlug(slug).map((r) => r.stableKey),
    ...listMachineResourcesForSlug(slug).map((r) => r.stableKey),
  ])
  return PROJECT_MACHINE_RELATIONS.filter((r) => keys.has(r.fromStableKey) && keys.has(r.toStableKey))
}
