/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IfoV3Interface extends utils.Interface {
  functions: {
    "CurrencyBNB()": FunctionFragment;
    "CurrencyETH()": FunctionFragment;
    "ILOToken()": FunctionFragment;
    "_name()": FunctionFragment;
    "bnbCommitted(address)": FunctionFragment;
    "buyBNB(uint256)": FunctionFragment;
    "buyETH(uint256)": FunctionFragment;
    "costPresaleBNB()": FunctionFragment;
    "costPresaleETH()": FunctionFragment;
    "decimals()": FunctionFragment;
    "endPresaleTime()": FunctionFragment;
    "hardcap()": FunctionFragment;
    "headerlogo()": FunctionFragment;
    "isInList(uint256)": FunctionFragment;
    "isWhitelistOn()": FunctionFragment;
    "link()": FunctionFragment;
    "listingPrice()": FunctionFragment;
    "logolink()": FunctionFragment;
    "maxUserAmount()": FunctionFragment;
    "owner()": FunctionFragment;
    "pause(bool)": FunctionFragment;
    "paused()": FunctionFragment;
    "removeWhitelistUsers()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setCompanyWallet(address)": FunctionFragment;
    "setCurrencyBNB(address)": FunctionFragment;
    "setCurrencyETH(address)": FunctionFragment;
    "setRound1(address,string,string,string,string,string,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,bool)": FunctionFragment;
    "setRound2(uint256,uint256,uint256,uint256,uint256,uint256,uint256,bool)": FunctionFragment;
    "setRound3(uint256,uint256,uint256,uint256,uint256,uint256,uint256,bool)": FunctionFragment;
    "setWhitelistedOn(bool)": FunctionFragment;
    "softcap()": FunctionFragment;
    "sold()": FunctionFragment;
    "startPresaleTime()": FunctionFragment;
    "status()": FunctionFragment;
    "symbol()": FunctionFragment;
    "totalWhitelisted()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "users()": FunctionFragment;
    "wallet()": FunctionFragment;
    "whitelistUser(uint256[])": FunctionFragment;
    "whitelisted(uint256)": FunctionFragment;
    "withdrawBNB()": FunctionFragment;
    "withdrawRemainingToken(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "CurrencyBNB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CurrencyETH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ILOToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "_name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bnbCommitted",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "buyBNB",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "costPresaleBNB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "costPresaleETH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "endPresaleTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "hardcap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "headerlogo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelistOn",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "link", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "listingPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "logolink", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxUserAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values: [boolean]): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeWhitelistUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCompanyWallet",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCurrencyBNB",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCurrencyETH",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setRound1",
    values: [
      string,
      string,
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setRound2",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setRound3",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelistedOn",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "softcap", values?: undefined): string;
  encodeFunctionData(functionFragment: "sold", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "startPresaleTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalWhitelisted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "users", values?: undefined): string;
  encodeFunctionData(functionFragment: "wallet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "whitelistUser",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelisted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBNB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRemainingToken",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "CurrencyBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CurrencyETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ILOToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bnbCommitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyBNB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "costPresaleBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "costPresaleETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "endPresaleTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hardcap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "headerlogo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isInList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelistOn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "link", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listingPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logolink", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxUserAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeWhitelistUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCompanyWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCurrencyBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCurrencyETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRound1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRound2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRound3", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelistedOn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "softcap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startPresaleTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRemainingToken",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface IfoV3 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IfoV3Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CurrencyBNB(overrides?: CallOverrides): Promise<[string]>;

    CurrencyETH(overrides?: CallOverrides): Promise<[string]>;

    ILOToken(overrides?: CallOverrides): Promise<[string]>;

    _name(overrides?: CallOverrides): Promise<[string]>;

    bnbCommitted(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    buyBNB(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    buyETH(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    costPresaleBNB(overrides?: CallOverrides): Promise<[BigNumber]>;

    costPresaleETH(overrides?: CallOverrides): Promise<[BigNumber]>;

    decimals(overrides?: CallOverrides): Promise<[BigNumber]>;

    endPresaleTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    hardcap(overrides?: CallOverrides): Promise<[BigNumber]>;

    headerlogo(overrides?: CallOverrides): Promise<[string]>;

    isInList(
      _addr: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isWhitelistOn(overrides?: CallOverrides): Promise<[boolean]>;

    link(overrides?: CallOverrides): Promise<[string]>;

    listingPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    logolink(overrides?: CallOverrides): Promise<[string]>;

    maxUserAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      _state: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    removeWhitelistUsers(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCompanyWallet(
      _companyWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCurrencyBNB(
      _addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCurrencyETH(
      _addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRound1(
      _ILOToken: string,
      _link: string,
      _logolink: string,
      _headerlogo: string,
      name: string,
      _symbol: string,
      _decimals: BigNumberish,
      _presaleCostBNB: BigNumberish,
      _presaleCostETH: BigNumberish,
      _listingPriceBNB: BigNumberish,
      _maxUserAmount: BigNumberish,
      _startPresaleTime: BigNumberish,
      _endPresaleTime: BigNumberish,
      _softcap: BigNumberish,
      _hardcap: BigNumberish,
      _isWhitelistOn: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRound2(
      _newCostBNB: BigNumberish,
      _newCostETH: BigNumberish,
      _maxUserAmount: BigNumberish,
      _startPresaleTime: BigNumberish,
      _endPresaleTime: BigNumberish,
      _softcap: BigNumberish,
      _hardcap: BigNumberish,
      _isWhitelistOn: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRound3(
      _newCostBNB: BigNumberish,
      _newCostETH: BigNumberish,
      _maxUserAmount: BigNumberish,
      _startPresaleTime: BigNumberish,
      _endPresaleTime: BigNumberish,
      _softcap: BigNumberish,
      _hardcap: BigNumberish,
      _isWhitelistOn: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setWhitelistedOn(
      val: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    softcap(overrides?: CallOverrides): Promise<[BigNumber]>;

    sold(overrides?: CallOverrides): Promise<[BigNumber]>;

    startPresaleTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    status(overrides?: CallOverrides): Promise<[BigNumber]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    totalWhitelisted(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    users(overrides?: CallOverrides): Promise<[BigNumber]>;

    wallet(overrides?: CallOverrides): Promise<[string]>;

    whitelistUser(
      _users: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    whitelisted(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawBNB(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawRemainingToken(
      token: string,
      _recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  CurrencyBNB(overrides?: CallOverrides): Promise<string>;

  CurrencyETH(overrides?: CallOverrides): Promise<string>;

  ILOToken(overrides?: CallOverrides): Promise<string>;

  _name(overrides?: CallOverrides): Promise<string>;

  bnbCommitted(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  buyBNB(
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  buyETH(
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  costPresaleBNB(overrides?: CallOverrides): Promise<BigNumber>;

  costPresaleETH(overrides?: CallOverrides): Promise<BigNumber>;

  decimals(overrides?: CallOverrides): Promise<BigNumber>;

  endPresaleTime(overrides?: CallOverrides): Promise<BigNumber>;

  hardcap(overrides?: CallOverrides): Promise<BigNumber>;

  headerlogo(overrides?: CallOverrides): Promise<string>;

  isInList(_addr: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  isWhitelistOn(overrides?: CallOverrides): Promise<boolean>;

  link(overrides?: CallOverrides): Promise<string>;

  listingPrice(overrides?: CallOverrides): Promise<BigNumber>;

  logolink(overrides?: CallOverrides): Promise<string>;

  maxUserAmount(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    _state: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  removeWhitelistUsers(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCompanyWallet(
    _companyWallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCurrencyBNB(
    _addr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCurrencyETH(
    _addr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRound1(
    _ILOToken: string,
    _link: string,
    _logolink: string,
    _headerlogo: string,
    name: string,
    _symbol: string,
    _decimals: BigNumberish,
    _presaleCostBNB: BigNumberish,
    _presaleCostETH: BigNumberish,
    _listingPriceBNB: BigNumberish,
    _maxUserAmount: BigNumberish,
    _startPresaleTime: BigNumberish,
    _endPresaleTime: BigNumberish,
    _softcap: BigNumberish,
    _hardcap: BigNumberish,
    _isWhitelistOn: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRound2(
    _newCostBNB: BigNumberish,
    _newCostETH: BigNumberish,
    _maxUserAmount: BigNumberish,
    _startPresaleTime: BigNumberish,
    _endPresaleTime: BigNumberish,
    _softcap: BigNumberish,
    _hardcap: BigNumberish,
    _isWhitelistOn: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRound3(
    _newCostBNB: BigNumberish,
    _newCostETH: BigNumberish,
    _maxUserAmount: BigNumberish,
    _startPresaleTime: BigNumberish,
    _endPresaleTime: BigNumberish,
    _softcap: BigNumberish,
    _hardcap: BigNumberish,
    _isWhitelistOn: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setWhitelistedOn(
    val: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  softcap(overrides?: CallOverrides): Promise<BigNumber>;

  sold(overrides?: CallOverrides): Promise<BigNumber>;

  startPresaleTime(overrides?: CallOverrides): Promise<BigNumber>;

  status(overrides?: CallOverrides): Promise<BigNumber>;

  symbol(overrides?: CallOverrides): Promise<string>;

  totalWhitelisted(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  users(overrides?: CallOverrides): Promise<BigNumber>;

  wallet(overrides?: CallOverrides): Promise<string>;

  whitelistUser(
    _users: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  whitelisted(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawBNB(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawRemainingToken(
    token: string,
    _recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    CurrencyBNB(overrides?: CallOverrides): Promise<string>;

    CurrencyETH(overrides?: CallOverrides): Promise<string>;

    ILOToken(overrides?: CallOverrides): Promise<string>;

    _name(overrides?: CallOverrides): Promise<string>;

    bnbCommitted(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    buyBNB(value: BigNumberish, overrides?: CallOverrides): Promise<void>;

    buyETH(value: BigNumberish, overrides?: CallOverrides): Promise<void>;

    costPresaleBNB(overrides?: CallOverrides): Promise<BigNumber>;

    costPresaleETH(overrides?: CallOverrides): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    endPresaleTime(overrides?: CallOverrides): Promise<BigNumber>;

    hardcap(overrides?: CallOverrides): Promise<BigNumber>;

    headerlogo(overrides?: CallOverrides): Promise<string>;

    isInList(_addr: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    isWhitelistOn(overrides?: CallOverrides): Promise<boolean>;

    link(overrides?: CallOverrides): Promise<string>;

    listingPrice(overrides?: CallOverrides): Promise<BigNumber>;

    logolink(overrides?: CallOverrides): Promise<string>;

    maxUserAmount(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(_state: boolean, overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    removeWhitelistUsers(overrides?: CallOverrides): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setCompanyWallet(
      _companyWallet: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setCurrencyBNB(_addr: string, overrides?: CallOverrides): Promise<void>;

    setCurrencyETH(_addr: string, overrides?: CallOverrides): Promise<void>;

    setRound1(
      _ILOToken: string,
      _link: string,
      _logolink: string,
      _headerlogo: string,
      name: string,
      _symbol: string,
      _decimals: BigNumberish,
      _presaleCostBNB: BigNumberish,
      _presaleCostETH: BigNumberish,
      _listingPriceBNB: BigNumberish,
      _maxUserAmount: BigNumberish,
      _startPresaleTime: BigNumberish,
      _endPresaleTime: BigNumberish,
      _softcap: BigNumberish,
      _hardcap: BigNumberish,
      _isWhitelistOn: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setRound2(
      _newCostBNB: BigNumberish,
      _newCostETH: BigNumberish,
      _maxUserAmount: BigNumberish,
      _startPresaleTime: BigNumberish,
      _endPresaleTime: BigNumberish,
      _softcap: BigNumberish,
      _hardcap: BigNumberish,
      _isWhitelistOn: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setRound3(
      _newCostBNB: BigNumberish,
      _newCostETH: BigNumberish,
      _maxUserAmount: BigNumberish,
      _startPresaleTime: BigNumberish,
      _endPresaleTime: BigNumberish,
      _softcap: BigNumberish,
      _hardcap: BigNumberish,
      _isWhitelistOn: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setWhitelistedOn(val: boolean, overrides?: CallOverrides): Promise<void>;

    softcap(overrides?: CallOverrides): Promise<BigNumber>;

    sold(overrides?: CallOverrides): Promise<BigNumber>;

    startPresaleTime(overrides?: CallOverrides): Promise<BigNumber>;

    status(overrides?: CallOverrides): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<string>;

    totalWhitelisted(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    users(overrides?: CallOverrides): Promise<BigNumber>;

    wallet(overrides?: CallOverrides): Promise<string>;

    whitelistUser(
      _users: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    whitelisted(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawBNB(overrides?: CallOverrides): Promise<void>;

    withdrawRemainingToken(
      token: string,
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    CurrencyBNB(overrides?: CallOverrides): Promise<BigNumber>;

    CurrencyETH(overrides?: CallOverrides): Promise<BigNumber>;

    ILOToken(overrides?: CallOverrides): Promise<BigNumber>;

    _name(overrides?: CallOverrides): Promise<BigNumber>;

    bnbCommitted(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    buyBNB(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    buyETH(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    costPresaleBNB(overrides?: CallOverrides): Promise<BigNumber>;

    costPresaleETH(overrides?: CallOverrides): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    endPresaleTime(overrides?: CallOverrides): Promise<BigNumber>;

    hardcap(overrides?: CallOverrides): Promise<BigNumber>;

    headerlogo(overrides?: CallOverrides): Promise<BigNumber>;

    isInList(
      _addr: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isWhitelistOn(overrides?: CallOverrides): Promise<BigNumber>;

    link(overrides?: CallOverrides): Promise<BigNumber>;

    listingPrice(overrides?: CallOverrides): Promise<BigNumber>;

    logolink(overrides?: CallOverrides): Promise<BigNumber>;

    maxUserAmount(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      _state: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    removeWhitelistUsers(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCompanyWallet(
      _companyWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCurrencyBNB(
      _addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCurrencyETH(
      _addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRound1(
      _ILOToken: string,
      _link: string,
      _logolink: string,
      _headerlogo: string,
      name: string,
      _symbol: string,
      _decimals: BigNumberish,
      _presaleCostBNB: BigNumberish,
      _presaleCostETH: BigNumberish,
      _listingPriceBNB: BigNumberish,
      _maxUserAmount: BigNumberish,
      _startPresaleTime: BigNumberish,
      _endPresaleTime: BigNumberish,
      _softcap: BigNumberish,
      _hardcap: BigNumberish,
      _isWhitelistOn: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRound2(
      _newCostBNB: BigNumberish,
      _newCostETH: BigNumberish,
      _maxUserAmount: BigNumberish,
      _startPresaleTime: BigNumberish,
      _endPresaleTime: BigNumberish,
      _softcap: BigNumberish,
      _hardcap: BigNumberish,
      _isWhitelistOn: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRound3(
      _newCostBNB: BigNumberish,
      _newCostETH: BigNumberish,
      _maxUserAmount: BigNumberish,
      _startPresaleTime: BigNumberish,
      _endPresaleTime: BigNumberish,
      _softcap: BigNumberish,
      _hardcap: BigNumberish,
      _isWhitelistOn: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setWhitelistedOn(
      val: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    softcap(overrides?: CallOverrides): Promise<BigNumber>;

    sold(overrides?: CallOverrides): Promise<BigNumber>;

    startPresaleTime(overrides?: CallOverrides): Promise<BigNumber>;

    status(overrides?: CallOverrides): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    totalWhitelisted(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    users(overrides?: CallOverrides): Promise<BigNumber>;

    wallet(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistUser(
      _users: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    whitelisted(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawBNB(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawRemainingToken(
      token: string,
      _recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CurrencyBNB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CurrencyETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ILOToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bnbCommitted(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyBNB(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    buyETH(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    costPresaleBNB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    costPresaleETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    endPresaleTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hardcap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    headerlogo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isInList(
      _addr: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isWhitelistOn(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    link(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    listingPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    logolink(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxUserAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      _state: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeWhitelistUsers(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCompanyWallet(
      _companyWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCurrencyBNB(
      _addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCurrencyETH(
      _addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRound1(
      _ILOToken: string,
      _link: string,
      _logolink: string,
      _headerlogo: string,
      name: string,
      _symbol: string,
      _decimals: BigNumberish,
      _presaleCostBNB: BigNumberish,
      _presaleCostETH: BigNumberish,
      _listingPriceBNB: BigNumberish,
      _maxUserAmount: BigNumberish,
      _startPresaleTime: BigNumberish,
      _endPresaleTime: BigNumberish,
      _softcap: BigNumberish,
      _hardcap: BigNumberish,
      _isWhitelistOn: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRound2(
      _newCostBNB: BigNumberish,
      _newCostETH: BigNumberish,
      _maxUserAmount: BigNumberish,
      _startPresaleTime: BigNumberish,
      _endPresaleTime: BigNumberish,
      _softcap: BigNumberish,
      _hardcap: BigNumberish,
      _isWhitelistOn: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRound3(
      _newCostBNB: BigNumberish,
      _newCostETH: BigNumberish,
      _maxUserAmount: BigNumberish,
      _startPresaleTime: BigNumberish,
      _endPresaleTime: BigNumberish,
      _softcap: BigNumberish,
      _hardcap: BigNumberish,
      _isWhitelistOn: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setWhitelistedOn(
      val: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    softcap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    startPresaleTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    status(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalWhitelisted(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    users(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wallet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    whitelistUser(
      _users: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    whitelisted(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawBNB(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawRemainingToken(
      token: string,
      _recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
