/** R111-A / R111A.3 canonical Command Center design tokens — do not deviate. */
export const CC_FONT_DISPLAY = "'Orbitron', sans-serif"
export const CC_FONT_BODY = "'Inter', sans-serif"

export const commandCenterLayout = {
  contentMax: '1180px',
  contentPaddingX: '32px',
  contentPaddingTop: '24px',
  contentPaddingTopMobile: '12px',
  contentPaddingBottom: '48px',
  sectionGap: '32px',
  sectionGapMobile: '20px',
  cardGap: '20px',
  cardRadius: '20px',
  headerHeight: 'auto',
  headerHeightMobile: 'auto',
  headerRow2MarginTop: '16px',
  headerSearchWidth: '380px',
  headerWalletWidth: '160px',
  headerChainWidth: '120px',
  headerControlsGap: '12px',
  briefingHeight: '156px',
  briefingHeightMobile: '39px',
  briefingPaddingTop: '24px',
  briefingPaddingX: '28px',
  briefingPaddingBottom: '24px',
  portfolioCardHeight: '160px',
  portfolioCardPadding: '24px',
  portfolioCardPaddingBottom: '14px',
  prioritiesHeight: '320px',
  prioritiesLeft: '65%',
  prioritiesRight: '35%',
  infraCardHeight: '180px',
  activityHeight: '340px',
  activityRowHeight: '72px',
  notificationsHeight: '240px',
  notificationRowHeight: '60px',
  settlementHeight: '180px',
  machineCollapsedHeight: '72px',
  machineExpandedHeight: '420px',
  mobileBottomPad: 'calc(96px + env(safe-area-inset-bottom, 0px))',
  stackBreakpoint: '1024px',
  mobileBreakpoint: '390px',
} as const

export const commandCenterColors = {
  pageBg: '#050505',
  cardBg: '#141414',
  cardBorder: '#2A2A2A',
  cardBorderHover: '#D4AF37',
  white: '#FFFFFF',
  subtitle: '#A3A3A3',
  body: '#E8E8E8',
  muted: '#8F8F8F',
  label: '#8C8C8C',
  portfolioHint: '#8E8E8E',
  prioritySubtitle: '#9D9D9D',
  divider: '#262626',
  gold: '#D4AF37',
  goldHover: '#E0C25A',
  pillBg: '#2A2110',
  pillBorder: '#6A5518',
  green: '#1BE77A',
  yellow: '#F4C542',
  gray: '#6F6F6F',
  transition: '180ms',
} as const

export const commandCenterType = {
  pageTitle: '52px',
  pageTitleLineHeight: '54px',
  pageTitleLetterSpacing: '-1px',
  sectionTitle: '18px',
  label: '13px',
  metric: '32px',
  metricInfra: '32px',
  description: '15px',
  subtitle: '16px',
  subtitleLineHeight: '24px',
  greeting: '48px',
  greetingMobile: '38px',
  portfolioDisconnected: '30px',
  portfolioLabel: '13px',
  lineHeight: 1.5,
} as const
