/** Command Center design tokens — DS001.1 foundations. */
import {
  ds001Colors,
  ds001FontFamily,
  ds001Layout,
  ds001Radius,
  ds001Spacing,
  ds001TypeRoles,
} from 'design-system/melega/tokens/ds001'

export const CC_FONT_DISPLAY = ds001FontFamily.display
export const CC_FONT_BODY = ds001FontFamily.body

export const commandCenterLayout = {
  contentMax: ds001Layout.contentMaxWidth,
  contentPaddingX: ds001Layout.pagePaddingX,
  contentPaddingTop: ds001Layout.pagePaddingTopBelowHeader,
  contentPaddingTopMobile: ds001Spacing[12],
  contentPaddingBottom: ds001Layout.pagePaddingBottom,
  sectionGap: ds001Spacing[32],
  sectionGapMobile: ds001Spacing[20],
  cardGap: ds001Spacing[20],
  cardRadius: ds001Radius.card,
  headerHeight: 'auto',
  headerHeightMobile: 'auto',
  headerRow2MarginTop: ds001Spacing[16],
  headerSearchWidth: '380px',
  headerWalletWidth: '160px',
  headerChainWidth: '120px',
  headerControlsGap: ds001Spacing[12],
  briefingHeight: '156px',
  briefingHeightMobile: '40px',
  briefingPaddingTop: ds001Spacing[24],
  briefingPaddingX: ds001Spacing[32],
  briefingPaddingBottom: ds001Spacing[24],
  portfolioCardHeight: '160px',
  portfolioCardPadding: ds001Spacing[24],
  portfolioCardPaddingBottom: ds001Spacing[16],
  prioritiesHeight: '320px',
  prioritiesLeft: '65%',
  prioritiesRight: '35%',
  infraCardHeight: '180px',
  activityHeight: '340px',
  activityRowHeight: '72px',
  notificationsHeight: '240px',
  notificationRowHeight: '64px',
  settlementHeight: '180px',
  machineCollapsedHeight: '72px',
  machineExpandedHeight: '420px',
  mobileBottomPad: 'calc(96px + env(safe-area-inset-bottom, 0px))',
  stackBreakpoint: '1024px',
  mobileBreakpoint: '390px',
} as const

export const commandCenterColors = {
  pageBg: ds001Colors.background,
  cardBg: ds001Colors.surface,
  cardBorder: ds001Colors.border,
  cardBorderHover: ds001Colors.cardHoverBorder,
  white: ds001Colors.primaryText,
  subtitle: ds001Colors.secondaryText,
  body: ds001Colors.primaryText,
  muted: ds001Colors.muted,
  label: ds001Colors.muted,
  portfolioHint: ds001Colors.muted,
  prioritySubtitle: ds001Colors.secondaryText,
  divider: ds001Colors.divider,
  gold: ds001Colors.primaryGold,
  goldHover: ds001Colors.hoverGold,
  pillBg: '#2A2110',
  pillBorder: '#6A5518',
  green: ds001Colors.success,
  yellow: ds001Colors.hoverGold,
  gray: ds001Colors.muted,
  transition: ds001Layout.cardTransition,
} as const

export const commandCenterType = {
  pageTitle: ds001TypeRoles.h1.size,
  pageTitleLineHeight: ds001TypeRoles.h1.lineHeight,
  pageTitleLetterSpacing: '-1px',
  sectionTitle: ds001TypeRoles.bodyLarge.size,
  label: ds001TypeRoles.caption.size,
  metric: ds001TypeRoles.h2.size,
  metricInfra: ds001TypeRoles.h2.size,
  description: ds001TypeRoles.body.size,
  subtitle: ds001TypeRoles.body.size,
  subtitleLineHeight: ds001TypeRoles.body.lineHeight,
  greeting: ds001TypeRoles.h1.size,
  greetingMobile: ds001TypeRoles.h2.size,
  portfolioDisconnected: ds001TypeRoles.h3.size,
  portfolioLabel: ds001TypeRoles.caption.size,
  lineHeight: 1.5,
} as const
