/**
 * Certified Project Ecosystem registry — PP009 read model.
 * ACTIVE only when backed by live capability or certified orchestration.
 */
import type { RegistryEcosystemRelationRecord, RegistryEcosystemServiceRecord } from './types'

export const PROJECT_ECOSYSTEM_SERVICES: RegistryEcosystemServiceRecord[] = [
  {
    stableKey: 'melega-dex.service.trade',
    projectSlug: 'melega-dex',
    category: 'DEX',
    type: 'WEB_APP',
    title: 'Trade / Swap',
    summary: 'Certified Melega DEX swap surface for project markets.',
    route: '/trade',
    externalUrl: null,
    lifecycle: 'ACTIVE',
    capabilities: ['tradable'],
    supportedChains: [56, 1, 137, 8453],
    evidenceClaimTypes: ['ASSET_IDENTITY', 'SUPPORTED_CHAIN'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['participate'],
    relatedUpdateStableKeys: ['melega-dex.markets-orchestration'],
    relatedDocumentationUrls: [],
    machineTags: ['swap', 'trade', 'pp005', 'dex'],
    iconKey: 'DEX',
    updatedAt: '2026-07-20T14:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.liquidity-studio',
    projectSlug: 'melega-dex',
    category: 'LIQUIDITY',
    type: 'WEB_APP',
    title: 'Liquidity Studio',
    summary: 'Add and manage liquidity through the existing Liquidity Studio.',
    route: '/liquidity-studio',
    externalUrl: null,
    lifecycle: 'ACTIVE',
    capabilities: ['liquidity'],
    supportedChains: [56],
    evidenceClaimTypes: ['SUPPORTED_CHAIN'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['participate'],
    relatedUpdateStableKeys: ['melega-dex.participation-farms-pools'],
    relatedDocumentationUrls: [],
    machineTags: ['liquidity', 'pp006', 'studio'],
    iconKey: 'LIQ',
    updatedAt: '2026-07-20T20:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.liquidity-building',
    projectSlug: 'melega-dex',
    category: 'LIQUIDITY',
    type: 'RUNTIME',
    title: 'Liquidity Building',
    summary: 'Discover Liquidity Building via the certified Studio deep link (activation may be blocked).',
    route: '/liquidity-studio?view=building',
    externalUrl: null,
    lifecycle: 'ACTIVE',
    capabilities: ['liquidity'],
    supportedChains: [56],
    evidenceClaimTypes: ['SUPPORTED_CHAIN', 'DEPLOYMENT_IDENTITY'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['participate'],
    relatedUpdateStableKeys: ['melega-dex.liquidity-building-discovery'],
    relatedDocumentationUrls: [],
    machineTags: ['liquidity-building', 'pp007'],
    iconKey: 'LB',
    updatedAt: '2026-07-20T22:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.farms',
    projectSlug: 'melega-dex',
    category: 'STAKING',
    type: 'WEB_APP',
    title: 'Farms',
    summary: 'Legacy MasterChef farms via the Farms studio.',
    route: '/farms',
    externalUrl: null,
    lifecycle: 'ACTIVE',
    capabilities: ['farm'],
    supportedChains: [56],
    evidenceClaimTypes: ['CONTRACT_IDENTITY', 'SUPPORTED_CHAIN'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['participate'],
    relatedUpdateStableKeys: ['melega-dex.participation-farms-pools'],
    relatedDocumentationUrls: [],
    machineTags: ['farms', 'pp006'],
    iconKey: 'FRM',
    updatedAt: '2026-07-20T20:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.pools',
    projectSlug: 'melega-dex',
    category: 'STAKING',
    type: 'WEB_APP',
    title: 'Pools',
    summary: 'MARCO staking pools via the Pools studio.',
    route: '/pools',
    externalUrl: null,
    lifecycle: 'ACTIVE',
    capabilities: ['pool'],
    supportedChains: [56],
    evidenceClaimTypes: ['CONTRACT_IDENTITY', 'SUPPORTED_CHAIN'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['participate'],
    relatedUpdateStableKeys: ['melega-dex.participation-farms-pools'],
    relatedDocumentationUrls: [],
    machineTags: ['pools', 'staking', 'pp006'],
    iconKey: 'POL',
    updatedAt: '2026-07-20T20:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.command-center',
    projectSlug: 'melega-dex',
    category: 'WALLET',
    type: 'WEB_APP',
    title: 'Command Center',
    summary: 'Wallet portfolio positions for liquidity, farms, and pools.',
    route: '/command-center',
    externalUrl: null,
    lifecycle: 'ACTIVE',
    capabilities: ['tradable', 'liquidity', 'farm', 'pool'],
    supportedChains: [56],
    evidenceClaimTypes: ['SUPPORTED_CHAIN'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['participate'],
    relatedUpdateStableKeys: [],
    relatedDocumentationUrls: [],
    machineTags: ['portfolio', 'pp004', 'command-center'],
    iconKey: 'CC',
    updatedAt: '2026-07-20T18:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.machine-manifest',
    projectSlug: 'melega-dex',
    category: 'API',
    type: 'API',
    title: 'Machine Manifest',
    summary: 'Static machine-readable project registry manifest.',
    route: '/registry/projects/melega-dex.json',
    externalUrl: null,
    lifecycle: 'ACTIVE',
    capabilities: ['machineManifest'],
    supportedChains: [56, 1, 137, 8453],
    evidenceClaimTypes: ['PROJECT_IDENTITY'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['trust'],
    relatedUpdateStableKeys: ['melega-dex.canonical-project-page-identity'],
    relatedDocumentationUrls: [],
    machineTags: ['manifest', 'api', 'machine'],
    iconKey: 'API',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.status',
    projectSlug: 'melega-dex',
    category: 'INFRASTRUCTURE',
    type: 'PORTAL',
    title: 'Platform Status',
    summary: 'Operational status surface for Melega DEX infrastructure.',
    route: '/status',
    externalUrl: null,
    lifecycle: 'ACTIVE',
    capabilities: [],
    supportedChains: [56],
    evidenceClaimTypes: ['SUPPORTED_CHAIN'],
    provenanceSourceClass: 'DERIVED',
    relatedSectionIds: [],
    relatedUpdateStableKeys: [],
    relatedDocumentationUrls: [],
    machineTags: ['status', 'infrastructure'],
    iconKey: 'INF',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.radar',
    projectSlug: 'melega-dex',
    category: 'ANALYTICS',
    type: 'WEB_APP',
    title: 'DEX Intelligence (Radar)',
    summary: 'Radar intelligence surface exists in product nav; registry capability remains planned.',
    route: '/radar',
    externalUrl: null,
    lifecycle: 'PLANNED',
    capabilities: ['radar'],
    supportedChains: [56],
    evidenceClaimTypes: ['SUPPORTED_CHAIN'],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: [],
    relatedUpdateStableKeys: [],
    relatedDocumentationUrls: [],
    machineTags: ['radar', 'intelligence', 'planned'],
    iconKey: 'RAD',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.build-studio',
    projectSlug: 'melega-dex',
    category: 'DEVELOPER',
    type: 'WEB_APP',
    title: 'Build Studio',
    summary: 'Platform build tooling surface; not capability-certified as project ACTIVE.',
    route: '/build-studio',
    externalUrl: null,
    lifecycle: 'PLANNED',
    capabilities: [],
    supportedChains: [56],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'DERIVED',
    relatedSectionIds: [],
    relatedUpdateStableKeys: [],
    relatedDocumentationUrls: [],
    machineTags: ['build-studio', 'developer', 'planned'],
    iconKey: 'DEV',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.ilo',
    projectSlug: 'melega-dex',
    category: 'LAUNCHPAD',
    type: 'WEB_APP',
    title: 'ILO / Launch',
    summary: 'ILO route exists with partial launch capability; not fully live.',
    route: '/ilo',
    externalUrl: null,
    lifecycle: 'PLANNED',
    capabilities: ['launch'],
    supportedChains: [56],
    evidenceClaimTypes: ['SUPPORTED_CHAIN'],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: [],
    relatedUpdateStableKeys: [],
    relatedDocumentationUrls: [],
    machineTags: ['ilo', 'launch', 'partial'],
    iconKey: 'LCH',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.labs',
    projectSlug: 'melega-dex',
    category: 'INFRASTRUCTURE',
    type: 'RUNTIME',
    title: 'Labs Runtime',
    summary: 'Experimental labs runtime route; registry capability planned.',
    route: '/runtime/labs',
    externalUrl: null,
    lifecycle: 'PLANNED',
    capabilities: ['labs'],
    supportedChains: [56],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'DERIVED',
    relatedSectionIds: [],
    relatedUpdateStableKeys: [],
    relatedDocumentationUrls: [],
    machineTags: ['labs', 'runtime', 'planned'],
    iconKey: 'LAB',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.treasury',
    projectSlug: 'melega-dex',
    category: 'TREASURY',
    type: 'SERVICE',
    title: 'Treasury Compatibility',
    summary: 'Treasury-compatible fee SKUs planned; no ACTIVE project product surface.',
    route: null,
    externalUrl: null,
    lifecycle: 'PLANNED',
    capabilities: ['treasuryCompatible'],
    supportedChains: [56],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: [],
    relatedUpdateStableKeys: [],
    relatedDocumentationUrls: [],
    machineTags: ['treasury', 'planned'],
    iconKey: 'TRY',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.smartdrop',
    projectSlug: 'melega-dex',
    category: 'MARKETPLACE',
    type: 'SERVICE',
    title: 'SmartDrop',
    summary: 'SmartDrop campaigns are planned with no dedicated product page.',
    route: null,
    externalUrl: null,
    lifecycle: 'UNAVAILABLE',
    capabilities: ['smartdrop'],
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: [],
    relatedUpdateStableKeys: [],
    relatedDocumentationUrls: [],
    machineTags: ['smartdrop', 'unavailable'],
    iconKey: 'SD',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.ai-report',
    projectSlug: 'melega-dex',
    category: 'AI',
    type: 'SERVICE',
    title: 'AI Report',
    summary: 'AI verification pipeline is not live in MVP.',
    route: null,
    externalUrl: null,
    lifecycle: 'UNAVAILABLE',
    capabilities: ['aiReport'],
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: [],
    relatedUpdateStableKeys: [],
    relatedDocumentationUrls: [],
    machineTags: ['ai', 'unavailable'],
    iconKey: 'AI',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.identity',
    projectSlug: 'melega-dex',
    category: 'IDENTITY',
    type: 'WEB_APP',
    title: 'Identity',
    summary: 'Platform identity surface; governance binding not claimed ACTIVE for this project.',
    route: '/identity',
    externalUrl: null,
    lifecycle: 'PLANNED',
    capabilities: [],
    supportedChains: [56],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'DERIVED',
    relatedSectionIds: ['trust'],
    relatedUpdateStableKeys: [],
    relatedDocumentationUrls: [],
    machineTags: ['identity', 'planned'],
    iconKey: 'ID',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.website',
    projectSlug: 'melega-dex',
    category: 'MEDIA',
    type: 'PORTAL',
    title: 'Official Website',
    summary: 'Official Melega Finance website from project registry.',
    route: null,
    externalUrl: 'https://www.melega.finance',
    lifecycle: 'ACTIVE',
    capabilities: [],
    supportedChains: [],
    evidenceClaimTypes: ['OFFICIAL_WEBSITE'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: [],
    relatedUpdateStableKeys: [],
    relatedDocumentationUrls: ['https://www.melega.finance'],
    machineTags: ['website', 'resources'],
    iconKey: 'WEB',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.docs',
    projectSlug: 'melega-dex',
    category: 'DOCUMENTATION',
    type: 'PORTAL',
    title: 'Documentation',
    summary: 'Official documentation / about surface from project registry.',
    route: null,
    externalUrl: 'https://www.melega.finance/about',
    lifecycle: 'ACTIVE',
    capabilities: [],
    supportedChains: [],
    evidenceClaimTypes: ['OFFICIAL_DOCUMENTATION'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: [],
    relatedUpdateStableKeys: ['melega-dex.provenance-evidence-framework'],
    relatedDocumentationUrls: ['https://www.melega.finance/about'],
    machineTags: ['docs', 'documentation'],
    iconKey: 'DOC',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
  {
    stableKey: 'melega-dex.service.space',
    projectSlug: 'melega-dex',
    category: 'COMMUNITY',
    type: 'PORTAL',
    title: 'Melega Space',
    summary: 'Community Space profile link; project bind not live.',
    route: null,
    externalUrl: 'https://melega.space/',
    lifecycle: 'PLANNED',
    capabilities: ['space'],
    supportedChains: [],
    evidenceClaimTypes: ['OFFICIAL_SOCIAL'],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: [],
    relatedUpdateStableKeys: [],
    relatedDocumentationUrls: [],
    machineTags: ['space', 'community', 'partial'],
    iconKey: 'SPC',
    updatedAt: '2026-07-18T16:00:00.000Z',
  },
]

export const PROJECT_ECOSYSTEM_RELATIONS: RegistryEcosystemRelationRecord[] = [
  {
    fromStableKey: 'melega-dex.service.trade',
    toStableKey: 'melega-dex.service.liquidity-studio',
    relationType: 'PROVIDES',
  },
  {
    fromStableKey: 'melega-dex.service.liquidity-studio',
    toStableKey: 'melega-dex.service.liquidity-building',
    relationType: 'COMPOSES',
  },
  {
    fromStableKey: 'melega-dex.service.trade',
    toStableKey: 'melega-dex.service.farms',
    relationType: 'PROVIDES',
  },
  {
    fromStableKey: 'melega-dex.service.command-center',
    toStableKey: 'melega-dex.service.liquidity-studio',
    relationType: 'USES',
  },
  {
    fromStableKey: 'melega-dex.service.command-center',
    toStableKey: 'melega-dex.service.farms',
    relationType: 'USES',
  },
  {
    fromStableKey: 'melega-dex.service.command-center',
    toStableKey: 'melega-dex.service.pools',
    relationType: 'USES',
  },
  {
    fromStableKey: 'melega-dex.service.treasury',
    toStableKey: 'melega-dex.service.identity',
    relationType: 'SECURES',
  },
  {
    fromStableKey: 'melega-dex.service.ai-report',
    toStableKey: 'melega-dex.service.machine-manifest',
    relationType: 'USES',
  },
  {
    fromStableKey: 'melega-dex.service.docs',
    toStableKey: 'melega-dex.service.machine-manifest',
    relationType: 'DOCUMENTS',
  },
  {
    fromStableKey: 'melega-dex.service.smartdrop',
    toStableKey: 'melega-dex.service.trade',
    relationType: 'USES',
  },
]

export function listEcosystemServicesForSlug(slug: string): RegistryEcosystemServiceRecord[] {
  return PROJECT_ECOSYSTEM_SERVICES.filter((row) => row.projectSlug === slug).map((row) => ({
    ...row,
    capabilities: [...row.capabilities],
    supportedChains: [...row.supportedChains],
    evidenceClaimTypes: [...row.evidenceClaimTypes],
    relatedSectionIds: [...row.relatedSectionIds],
    relatedUpdateStableKeys: [...row.relatedUpdateStableKeys],
    relatedDocumentationUrls: [...row.relatedDocumentationUrls],
    machineTags: [...row.machineTags],
  }))
}

export function listEcosystemRelationsForSlug(slug: string): RegistryEcosystemRelationRecord[] {
  const keys = new Set(listEcosystemServicesForSlug(slug).map((s) => s.stableKey))
  return PROJECT_ECOSYSTEM_RELATIONS.filter((r) => keys.has(r.fromStableKey) && keys.has(r.toStableKey)).map((r) => ({
    ...r,
  }))
}
