/**
 * KERL Remote Contract Compatibility Certification — Phase 6 handshake constants.
 * Local validation only — no Swarm runtime imports.
 */
export const KERL_REMOTE_CONTRACT_COMPATIBILITY_CERTIFIED =
  'KERL_REMOTE_CONTRACT_COMPATIBILITY_CERTIFIED' as const

export const COMPATIBILITY_OUTCOME_COMPATIBLE = 'compatible' as const
export const COMPATIBILITY_OUTCOME_UNKNOWN = 'unknown' as const
export const COMPATIBILITY_OUTCOME_INCOMPATIBLE = 'incompatible' as const

export const COMPATIBILITY_CERTIFICATION_OUTCOMES = [
  COMPATIBILITY_OUTCOME_COMPATIBLE,
  COMPATIBILITY_OUTCOME_UNKNOWN,
  COMPATIBILITY_OUTCOME_INCOMPATIBLE,
] as const

export type CompatibilityCertificationOutcome = (typeof COMPATIBILITY_CERTIFICATION_OUTCOMES)[number]

export const HANDSHAKE_ERROR_CODES = {
  MISSING_CERTIFICATION: 'HANDSHAKE_MISSING_CERTIFICATION',
  CERTIFICATION_UNKNOWN: 'HANDSHAKE_CERTIFICATION_UNKNOWN',
  CERTIFICATION_INCOMPATIBLE: 'HANDSHAKE_CERTIFICATION_INCOMPATIBLE',
  INVALID_CERTIFICATION_VERDICT: 'HANDSHAKE_INVALID_CERTIFICATION_VERDICT',
  VERSION_MISMATCH: 'HANDSHAKE_VERSION_MISMATCH',
  IDENTITY_MISMATCH: 'HANDSHAKE_IDENTITY_MISMATCH',
  MISSING_SUPPRESSION_FIELDS: 'HANDSHAKE_MISSING_SUPPRESSION_FIELDS',
  INVALID_MANIFEST: 'HANDSHAKE_INVALID_MANIFEST',
  PROPOSAL_INELIGIBLE: 'HANDSHAKE_PROPOSAL_INELIGIBLE',
  MISSING_RC1_ENVELOPE: 'HANDSHAKE_MISSING_RC1_ENVELOPE',
} as const
