/** KERL testnet execution handoff — Phase T2 genesis execution. */
export const HANDOFF_MODE_TESTNET_EXECUTION = 'testnet_execution' as const

export const TESTNET_EXECUTION_MANIFEST_MODE = 'TESTNET_EXECUTION_ONLY' as const

export const TESTNET_HANDOFF_ERROR_CODES = {
  INVALID_PACKAGE: 'TESTNET_HANDOFF_INVALID_PACKAGE',
  NOT_TESTNET_MODE: 'TESTNET_HANDOFF_NOT_TESTNET_MODE',
  EXECUTION_NOT_PERMITTED: 'TESTNET_HANDOFF_EXECUTION_NOT_PERMITTED',
  WRONG_CHAIN: 'TESTNET_HANDOFF_WRONG_CHAIN',
  IDENTITY_MISMATCH: 'TESTNET_HANDOFF_IDENTITY_MISMATCH',
  MISSING_INSTRUCTION: 'TESTNET_HANDOFF_MISSING_INSTRUCTION',
} as const
