/**
 * Canonical KERL testnet activation lifecycle.
 * Execution wallet submission is permitted only in TESTNET_EXECUTION_ENABLED or TESTNET_EXECUTION_ACTIVE.
 * MAINNET paths are constitutionally disabled.
 */

export const ACTIVATION_LIFECYCLE_OFF = 'OFF' as const
export const ACTIVATION_LIFECYCLE_DRY_RUN = 'DRY_RUN' as const
export const ACTIVATION_LIFECYCLE_TESTNET_ARMED = 'TESTNET_ARMED' as const
export const ACTIVATION_LIFECYCLE_TESTNET_EXECUTION_ENABLED = 'TESTNET_EXECUTION_ENABLED' as const
export const ACTIVATION_LIFECYCLE_TESTNET_EXECUTION_ACTIVE = 'TESTNET_EXECUTION_ACTIVE' as const
export const ACTIVATION_LIFECYCLE_TESTNET_RECEIPT_CAPTURE = 'TESTNET_RECEIPT_CAPTURE' as const
export const ACTIVATION_LIFECYCLE_EXECUTION_EVIDENCE = 'EXECUTION_EVIDENCE' as const
export const ACTIVATION_LIFECYCLE_SETTLEMENT_EVENT_READY = 'SETTLEMENT_EVENT_READY' as const

export const ACTIVATION_LIFECYCLE_STATES = [
  ACTIVATION_LIFECYCLE_OFF,
  ACTIVATION_LIFECYCLE_DRY_RUN,
  ACTIVATION_LIFECYCLE_TESTNET_ARMED,
  ACTIVATION_LIFECYCLE_TESTNET_EXECUTION_ENABLED,
  ACTIVATION_LIFECYCLE_TESTNET_EXECUTION_ACTIVE,
  ACTIVATION_LIFECYCLE_TESTNET_RECEIPT_CAPTURE,
  ACTIVATION_LIFECYCLE_EXECUTION_EVIDENCE,
  ACTIVATION_LIFECYCLE_SETTLEMENT_EVENT_READY,
] as const

export type ActivationLifecycleState = (typeof ACTIVATION_LIFECYCLE_STATES)[number]

/** Ordered progression — no skipping; rollback returns to DRY_RUN only before wallet submission. */
export const ACTIVATION_LIFECYCLE_TRANSITIONS: Readonly<
  Record<ActivationLifecycleState, readonly ActivationLifecycleState[]>
> = {
  [ACTIVATION_LIFECYCLE_OFF]: [ACTIVATION_LIFECYCLE_DRY_RUN],
  [ACTIVATION_LIFECYCLE_DRY_RUN]: [ACTIVATION_LIFECYCLE_TESTNET_ARMED],
  [ACTIVATION_LIFECYCLE_TESTNET_ARMED]: [ACTIVATION_LIFECYCLE_TESTNET_EXECUTION_ENABLED],
  [ACTIVATION_LIFECYCLE_TESTNET_EXECUTION_ENABLED]: [ACTIVATION_LIFECYCLE_TESTNET_EXECUTION_ACTIVE],
  [ACTIVATION_LIFECYCLE_TESTNET_EXECUTION_ACTIVE]: [ACTIVATION_LIFECYCLE_TESTNET_RECEIPT_CAPTURE],
  [ACTIVATION_LIFECYCLE_TESTNET_RECEIPT_CAPTURE]: [ACTIVATION_LIFECYCLE_EXECUTION_EVIDENCE],
  [ACTIVATION_LIFECYCLE_EXECUTION_EVIDENCE]: [ACTIVATION_LIFECYCLE_SETTLEMENT_EVENT_READY],
  [ACTIVATION_LIFECYCLE_SETTLEMENT_EVENT_READY]: [],
}

export function lifecyclePermitsWalletSubmission(state: ActivationLifecycleState): boolean {
  return (
    state === ACTIVATION_LIFECYCLE_TESTNET_EXECUTION_ENABLED ||
    state === ACTIVATION_LIFECYCLE_TESTNET_EXECUTION_ACTIVE
  )
}

export function lifecyclePermitsDryRunOnly(state: ActivationLifecycleState): boolean {
  return state === ACTIVATION_LIFECYCLE_DRY_RUN
}

export function lifecycleIsArmedOnly(state: ActivationLifecycleState): boolean {
  return state === ACTIVATION_LIFECYCLE_TESTNET_ARMED
}

export function lifecycleIsPreExecution(state: ActivationLifecycleState): boolean {
  return (
    state === ACTIVATION_LIFECYCLE_OFF ||
    state === ACTIVATION_LIFECYCLE_DRY_RUN ||
    state === ACTIVATION_LIFECYCLE_TESTNET_ARMED
  )
}

export function canTransitionLifecycle(
  from: ActivationLifecycleState,
  to: ActivationLifecycleState,
): boolean {
  return ACTIVATION_LIFECYCLE_TRANSITIONS[from].includes(to)
}
