/**
 * M6 mainnet canary operating state.
 * Broadcast is forbidden unless preflight matches M5 bytecode and a signer is present.
 */

import { PROTOCOL_FEE_STATE } from './fee'
import { ACTIVE_V2_ROLLOUT, V2_ROLLOUT_STATE } from './m4OperatingState'

export const M6_VERDICT = {
  AWAITING_FOUNDER_MAINNET_AUTHORIZATION: 'MELEGASWAP_V2_SMARTSWAP_M6_AWAITING_FOUNDER_MAINNET_AUTHORIZATION',
  BLOCKED_PREFLIGHT_DRIFT: 'MELEGASWAP_V2_SMARTSWAP_M6_BLOCKED_PREFLIGHT_DRIFT',
  EXECUTOR_DEPLOYMENT_CERTIFICATION_FAILED: 'MELEGASWAP_V2_SMARTSWAP_M6_EXECUTOR_DEPLOYMENT_CERTIFICATION_FAILED',
  CANARY_FAILED: 'MELEGASWAP_V2_SMARTSWAP_M6_BNB_MAINNET_CANARY_FAILED',
  CERTIFIED: 'MELEGASWAP_V2_SMARTSWAP_UNIVERSAL_ENGINE_M6_BNB_MAINNET_CANARY_CERTIFIED',
} as const

export const M6_ACTIVE_VERDICT = M6_VERDICT.BLOCKED_PREFLIGHT_DRIFT

export const V2_M6_BROADCAST_FORBIDDEN = 'V2_M6_BROADCAST_FORBIDDEN' as const
export const V2_M6_FEE_VERIFIED_FORBIDDEN = 'V2_M6_FEE_VERIFIED_FORBIDDEN' as const

export function assertM6NoBroadcast(): never {
  throw new Error(V2_M6_BROADCAST_FORBIDDEN)
}

export function assertM6NeverFeeVerifiedWithoutMainnetProof(): never {
  throw new Error(V2_M6_FEE_VERIFIED_FORBIDDEN)
}

export function m6LegacyProductionStillAuthoritative(): boolean {
  return ACTIVE_V2_ROLLOUT === V2_ROLLOUT_STATE.LEGACY_PRODUCTION
}

export const M6_FEE_STATE = {
  before: PROTOCOL_FEE_STATE.FEE_ENFORCEABLE,
  after: PROTOCOL_FEE_STATE.FEE_ENFORCEABLE,
} as const
