/**
 * Certified Developer & Documentation Hub registry — PP010 read model.
 * ACTIVE only when a live public route/URL exists.
 */
import type { RegistryDeveloperRelationRecord, RegistryDeveloperResourceRecord } from './types'

const BSC = [56] as number[]
const MULTI = [56, 1, 137, 8453] as number[]

function apiResource(
  key: string,
  title: string,
  summary: string,
  route: string,
  relatedSectionIds: string[],
  relatedServiceStableKeys: string[] = [],
  relatedUpdateStableKeys: string[] = [],
): RegistryDeveloperResourceRecord {
  return {
    stableKey: key,
    projectSlug: 'melega-dex',
    category: 'API',
    type: 'ENDPOINT',
    title,
    summary,
    version: '1.0.0',
    url: null,
    route,
    lifecycle: 'ACTIVE',
    machineReadable: true,
    supportedChains: MULTI,
    evidenceClaimTypes: ['PROJECT_IDENTITY'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds,
    relatedServiceStableKeys,
    relatedUpdateStableKeys,
    machineTags: ['api', 'public', 'json'],
    updatedAt: '2026-07-20T23:00:00.000Z',
    contractAddress: null,
  }
}

export const PROJECT_DEVELOPER_RESOURCES: RegistryDeveloperResourceRecord[] = [
  {
    stableKey: 'melega-dex.dev.docs-about',
    projectSlug: 'melega-dex',
    category: 'DOCUMENTATION',
    type: 'HTML',
    title: 'Documentation (About)',
    summary: 'Official About / documentation landing from the project registry docsUrl.',
    version: '1.0.0',
    url: 'https://www.melega.finance/about',
    route: null,
    lifecycle: 'ACTIVE',
    machineReadable: false,
    supportedChains: [],
    evidenceClaimTypes: ['OFFICIAL_DOCUMENTATION'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: ['melega-dex.service.docs'],
    relatedUpdateStableKeys: ['melega-dex.provenance-evidence-framework'],
    machineTags: ['docs', 'about', 'documentation'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.registry-spec',
    projectSlug: 'melega-dex',
    category: 'REFERENCE',
    type: 'MARKDOWN',
    title: 'Project Registry Core Spec',
    summary: 'Canonical registry specification referenced by agent discovery well-known.',
    version: '1.0.0',
    url: 'https://github.com/meleganza/MelegaSwapV2/blob/main/docs/MELEGA_DEX_PROJECT_REGISTRY_CORE_SPEC_V1.md',
    route: null,
    lifecycle: 'ACTIVE',
    machineReadable: false,
    supportedChains: [],
    evidenceClaimTypes: ['OFFICIAL_REPOSITORY'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: ['melega-dex.service.machine-manifest'],
    relatedUpdateStableKeys: ['melega-dex.canonical-project-page-identity'],
    machineTags: ['registry', 'spec', 'markdown'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.faq',
    projectSlug: 'melega-dex',
    category: 'FAQ',
    type: 'HTML',
    title: 'Project FAQ',
    summary: 'Dedicated FAQ documentation is not published as a separate surface yet.',
    version: '0.0.0',
    url: null,
    route: null,
    lifecycle: 'PLANNED',
    machineReadable: false,
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: [],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    machineTags: ['faq', 'planned'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.whitepaper',
    projectSlug: 'melega-dex',
    category: 'WHITEPAPER',
    type: 'PDF',
    title: 'Whitepaper',
    summary: 'No certified whitepaper URL is registered for Melega DEX.',
    version: '0.0.0',
    url: null,
    route: null,
    lifecycle: 'UNAVAILABLE',
    machineReadable: false,
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'UNKNOWN',
    relatedSectionIds: [],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    machineTags: ['whitepaper', 'unavailable'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  apiResource(
    'melega-dex.dev.api.project-page',
    'Public Project Document API',
    'Canonical project page JSON including additive PP002–PP009 summaries.',
    '/api/public/projects/melega-dex/',
    ['overview', 'ecosystem'],
    ['melega-dex.service.machine-manifest'],
    ['melega-dex.canonical-project-page-identity'],
  ),
  apiResource(
    'melega-dex.dev.api.evidence',
    'Evidence Pack API',
    'Public PP002 evidence pack for provenance and verification.',
    '/api/public/projects/melega-dex/evidence/',
    ['trust'],
    [],
    ['melega-dex.provenance-evidence-framework'],
  ),
  apiResource(
    'melega-dex.dev.api.readiness',
    'Readiness API',
    'Public PP003 readiness and trust snapshot document.',
    '/api/public/projects/melega-dex/readiness/',
    ['trust'],
  ),
  apiResource(
    'melega-dex.dev.api.markets',
    'Markets API',
    'Public PP005 markets orchestration document.',
    '/api/public/projects/melega-dex/markets/',
    ['participate'],
    ['melega-dex.service.trade'],
    ['melega-dex.markets-orchestration'],
  ),
  apiResource(
    'melega-dex.dev.api.participation',
    'Participation API',
    'Public PP006 liquidity / farms / pools participation document.',
    '/api/public/projects/melega-dex/participation/',
    ['participate'],
    ['melega-dex.service.liquidity-studio', 'melega-dex.service.farms', 'melega-dex.service.pools'],
    ['melega-dex.participation-farms-pools'],
  ),
  apiResource(
    'melega-dex.dev.api.liquidity-building',
    'Liquidity Building API',
    'Public PP007 Liquidity Building orchestration document.',
    '/api/public/projects/melega-dex/liquidity-building/',
    ['participate'],
    ['melega-dex.service.liquidity-building'],
    ['melega-dex.liquidity-building-discovery'],
  ),
  apiResource(
    'melega-dex.dev.api.updates',
    'Updates API',
    'Public PP008 verified updates timeline document.',
    '/api/public/projects/melega-dex/updates/',
    ['updates'],
  ),
  apiResource(
    'melega-dex.dev.api.ecosystem',
    'Ecosystem Graph API',
    'Public PP009 ecosystem services and relationships document.',
    '/api/public/projects/melega-dex/ecosystem/',
    ['ecosystem'],
    ['melega-dex.service.machine-manifest'],
  ),
  {
    stableKey: 'melega-dex.dev.machine-manifest',
    projectSlug: 'melega-dex',
    category: 'SCHEMA',
    type: 'JSON',
    title: 'Machine Manifest',
    summary: 'Static machine-readable project registry manifest.',
    version: '1.0.0',
    url: null,
    route: '/registry/projects/melega-dex.json',
    lifecycle: 'ACTIVE',
    machineReadable: true,
    supportedChains: MULTI,
    evidenceClaimTypes: ['PROJECT_IDENTITY'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['ecosystem', 'trust'],
    relatedServiceStableKeys: ['melega-dex.service.machine-manifest'],
    relatedUpdateStableKeys: ['melega-dex.canonical-project-page-identity'],
    machineTags: ['manifest', 'json', 'schema'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.registry-index',
    projectSlug: 'melega-dex',
    category: 'API',
    type: 'JSON',
    title: 'Project Registry Index',
    summary: 'Static index of registered projects.',
    version: '1.0.0',
    url: null,
    route: '/registry/projects/index.json',
    lifecycle: 'ACTIVE',
    machineReadable: true,
    supportedChains: [],
    evidenceClaimTypes: ['PROJECT_IDENTITY'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    machineTags: ['registry', 'index', 'json'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.discovery-index',
    projectSlug: 'melega-dex',
    category: 'API',
    type: 'JSON',
    title: 'Project Discovery Index',
    summary: 'Static discovery index for agents and integrators.',
    version: '1.0.0',
    url: null,
    route: '/registry/projects/discovery.json',
    lifecycle: 'ACTIVE',
    machineReadable: true,
    supportedChains: [],
    evidenceClaimTypes: ['PROJECT_IDENTITY'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    machineTags: ['discovery', 'json'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.agent-discovery',
    projectSlug: 'melega-dex',
    category: 'AI_MANIFEST',
    type: 'JSON',
    title: 'Well-known Agent Discovery',
    summary: 'Well-known discovery document for AI agents and integrators.',
    version: '1.0.0',
    url: null,
    route: '/.well-known/melega-dex-discovery.json',
    lifecycle: 'ACTIVE',
    machineReadable: true,
    supportedChains: [],
    evidenceClaimTypes: ['PROJECT_IDENTITY'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: ['melega-dex.service.machine-manifest'],
    relatedUpdateStableKeys: [],
    machineTags: ['ai', 'discovery', 'well-known'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.contract.factory',
    projectSlug: 'melega-dex',
    category: 'CONTRACT',
    type: 'ABI',
    title: 'Melega Factory (BSC)',
    summary: 'Official AMM factory contract address used by Melega DEX on BSC.',
    version: '1.0.0',
    url: null,
    route: null,
    lifecycle: 'ACTIVE',
    machineReadable: true,
    supportedChains: BSC,
    evidenceClaimTypes: ['CONTRACT_IDENTITY', 'SUPPORTED_CHAIN'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: ['melega-dex.service.trade', 'melega-dex.service.liquidity-studio'],
    relatedUpdateStableKeys: [],
    machineTags: ['factory', 'amm', 'bsc', 'contract'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: '0xb7e5848e1d0cb457f2026670fcb9bbdb7e9e039c',
  },
  {
    stableKey: 'melega-dex.dev.contract.router',
    projectSlug: 'melega-dex',
    category: 'CONTRACT',
    type: 'ABI',
    title: 'Melega Router (BSC)',
    summary: 'Official router contract address used by Melega DEX on BSC.',
    version: '1.0.0',
    url: null,
    route: null,
    lifecycle: 'ACTIVE',
    machineReadable: true,
    supportedChains: BSC,
    evidenceClaimTypes: ['CONTRACT_IDENTITY', 'SUPPORTED_CHAIN'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['participate', 'ecosystem'],
    relatedServiceStableKeys: ['melega-dex.service.trade'],
    relatedUpdateStableKeys: ['melega-dex.markets-orchestration'],
    machineTags: ['router', 'amm', 'bsc', 'contract'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: '0xc25033218d181b27d4a2944fbb04fc055da4eab3',
  },
  {
    stableKey: 'melega-dex.dev.contract.masterchef',
    projectSlug: 'melega-dex',
    category: 'CONTRACT',
    type: 'ABI',
    title: 'MasterChef (BSC)',
    summary: 'Official MasterChef contract address for Melega farms on BSC.',
    version: '1.0.0',
    url: null,
    route: null,
    lifecycle: 'ACTIVE',
    machineReadable: true,
    supportedChains: BSC,
    evidenceClaimTypes: ['CONTRACT_IDENTITY', 'SUPPORTED_CHAIN'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['participate', 'ecosystem'],
    relatedServiceStableKeys: ['melega-dex.service.farms'],
    relatedUpdateStableKeys: ['melega-dex.participation-farms-pools'],
    machineTags: ['masterchef', 'farms', 'bsc', 'contract'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: '0x41d5487836452d23f2c467070244e5842b412794',
  },
  {
    stableKey: 'melega-dex.dev.deployment.bsc',
    projectSlug: 'melega-dex',
    category: 'DEPLOYMENT',
    type: 'JSON',
    title: 'BSC Mainnet Deployment',
    summary: 'Primary Melega DEX deployment on BNB Smart Chain (eip155:56).',
    version: '1.0.0',
    url: null,
    route: null,
    lifecycle: 'ACTIVE',
    machineReadable: true,
    supportedChains: BSC,
    evidenceClaimTypes: ['DEPLOYMENT_IDENTITY', 'SUPPORTED_CHAIN'],
    provenanceSourceClass: 'MELEGA_VERIFIED',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    machineTags: ['deployment', 'bsc', 'eip155:56'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.abi-catalog',
    projectSlug: 'melega-dex',
    category: 'ABI',
    type: 'ABI',
    title: 'Public ABI Catalog',
    summary: 'ABIs exist in-repo under apps/web/src/config/abi/; no dedicated public ABI catalog URL yet.',
    version: '0.0.0',
    url: null,
    route: null,
    lifecycle: 'PLANNED',
    machineReadable: true,
    supportedChains: BSC,
    evidenceClaimTypes: [],
    provenanceSourceClass: 'DERIVED',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    machineTags: ['abi', 'catalog', 'planned'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.sdk.swap',
    projectSlug: 'melega-dex',
    category: 'SDK',
    type: 'REPOSITORY',
    title: 'Swap SDK Packages',
    summary: 'Monorepo swap-sdk packages exist; no published @melega SDK package is certified ACTIVE.',
    version: '0.0.0',
    url: null,
    route: null,
    lifecycle: 'PLANNED',
    machineReadable: false,
    supportedChains: MULTI,
    evidenceClaimTypes: [],
    provenanceSourceClass: 'DERIVED',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: ['melega-dex.service.trade'],
    relatedUpdateStableKeys: [],
    machineTags: ['sdk', 'swap-sdk', 'planned'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.example.integration',
    projectSlug: 'melega-dex',
    category: 'EXAMPLE',
    type: 'MARKDOWN',
    title: 'Integration Examples',
    summary: 'Curated public integration examples are not published yet.',
    version: '0.0.0',
    url: null,
    route: null,
    lifecycle: 'PLANNED',
    machineReadable: false,
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'PROJECT_ATTESTED',
    relatedSectionIds: [],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    machineTags: ['example', 'planned'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.openapi',
    projectSlug: 'melega-dex',
    category: 'OPENAPI',
    type: 'OPENAPI',
    title: 'OpenAPI Specification',
    summary: 'No OpenAPI specification is published for Melega public project APIs.',
    version: '0.0.0',
    url: null,
    route: null,
    lifecycle: 'UNAVAILABLE',
    machineReadable: true,
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'UNKNOWN',
    relatedSectionIds: [],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    machineTags: ['openapi', 'unavailable'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.graphql',
    projectSlug: 'melega-dex',
    category: 'GRAPHQL',
    type: 'GRAPHQL',
    title: 'Melega Subgraph GraphQL',
    summary: 'Subgraph URL is environment-gated (NEXT_PUBLIC_MELEGA_SUBGRAPH_URL); not certified ACTIVE.',
    version: '0.0.0',
    url: null,
    route: null,
    lifecycle: 'PLANNED',
    machineReadable: true,
    supportedChains: BSC,
    evidenceClaimTypes: [],
    provenanceSourceClass: 'DERIVED',
    relatedSectionIds: [],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    machineTags: ['graphql', 'subgraph', 'planned'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.rpc',
    projectSlug: 'melega-dex',
    category: 'RPC',
    type: 'ENDPOINT',
    title: 'Public Integrator RPC',
    summary: 'No dedicated public RPC endpoint is published for third-party integrators.',
    version: '0.0.0',
    url: null,
    route: null,
    lifecycle: 'UNAVAILABLE',
    machineReadable: false,
    supportedChains: BSC,
    evidenceClaimTypes: [],
    provenanceSourceClass: 'UNKNOWN',
    relatedSectionIds: [],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    machineTags: ['rpc', 'unavailable'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.webhooks',
    projectSlug: 'melega-dex',
    category: 'WEBHOOK',
    type: 'ENDPOINT',
    title: 'Project Webhooks',
    summary: 'No project webhook endpoints exist in the repository.',
    version: '0.0.0',
    url: null,
    route: null,
    lifecycle: 'UNAVAILABLE',
    machineReadable: false,
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'UNKNOWN',
    relatedSectionIds: [],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    machineTags: ['webhook', 'unavailable'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.mcp',
    projectSlug: 'melega-dex',
    category: 'MCP',
    type: 'ENDPOINT',
    title: 'MCP Agent Surface',
    summary: 'MCP tooling for Melega DEX is not available as a certified public surface.',
    version: '0.0.0',
    url: null,
    route: null,
    lifecycle: 'UNAVAILABLE',
    machineReadable: true,
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'UNKNOWN',
    relatedSectionIds: [],
    relatedServiceStableKeys: [],
    relatedUpdateStableKeys: [],
    machineTags: ['mcp', 'ai', 'unavailable'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
  {
    stableKey: 'melega-dex.dev.build-studio-ai-manifest',
    projectSlug: 'melega-dex',
    category: 'AI_MANIFEST',
    type: 'JSON',
    title: 'Build Studio AI Manifest UI',
    summary: 'Build Studio exposes an AI Manifest panel; not a certified project-level AI integration API.',
    version: '0.0.0',
    url: null,
    route: '/build-studio',
    lifecycle: 'PLANNED',
    machineReadable: true,
    supportedChains: [],
    evidenceClaimTypes: [],
    provenanceSourceClass: 'DERIVED',
    relatedSectionIds: ['ecosystem'],
    relatedServiceStableKeys: ['melega-dex.service.build-studio'],
    relatedUpdateStableKeys: [],
    machineTags: ['ai-manifest', 'build-studio', 'planned'],
    updatedAt: '2026-07-18T16:00:00.000Z',
    contractAddress: null,
  },
]

export const PROJECT_DEVELOPER_RELATIONS: RegistryDeveloperRelationRecord[] = [
  {
    fromStableKey: 'melega-dex.dev.docs-about',
    toStableKey: 'melega-dex.dev.machine-manifest',
    relationType: 'DOCUMENTS',
  },
  {
    fromStableKey: 'melega-dex.dev.registry-spec',
    toStableKey: 'melega-dex.dev.machine-manifest',
    relationType: 'DESCRIBES',
  },
  {
    fromStableKey: 'melega-dex.dev.api.project-page',
    toStableKey: 'melega-dex.dev.machine-manifest',
    relationType: 'USES',
  },
  {
    fromStableKey: 'melega-dex.dev.api.ecosystem',
    toStableKey: 'melega-dex.dev.machine-manifest',
    relationType: 'USES',
  },
  {
    fromStableKey: 'melega-dex.dev.agent-discovery',
    toStableKey: 'melega-dex.dev.discovery-index',
    relationType: 'USES',
  },
  {
    fromStableKey: 'melega-dex.dev.contract.router',
    toStableKey: 'melega-dex.dev.contract.factory',
    relationType: 'USES',
  },
  {
    fromStableKey: 'melega-dex.dev.contract.masterchef',
    toStableKey: 'melega-dex.dev.deployment.bsc',
    relationType: 'IMPLEMENTS',
  },
  {
    fromStableKey: 'melega-dex.dev.api.markets',
    toStableKey: 'melega-dex.dev.contract.router',
    relationType: 'DESCRIBES',
  },
  {
    fromStableKey: 'melega-dex.dev.sdk.swap',
    toStableKey: 'melega-dex.dev.api.markets',
    relationType: 'USES',
  },
  {
    fromStableKey: 'melega-dex.dev.build-studio-ai-manifest',
    toStableKey: 'melega-dex.dev.agent-discovery',
    relationType: 'USES',
  },
]

export function listDeveloperResourcesForSlug(slug: string): RegistryDeveloperResourceRecord[] {
  return PROJECT_DEVELOPER_RESOURCES.filter((row) => row.projectSlug === slug).map((row) => ({
    ...row,
    supportedChains: [...row.supportedChains],
    evidenceClaimTypes: [...row.evidenceClaimTypes],
    relatedSectionIds: [...row.relatedSectionIds],
    relatedServiceStableKeys: [...row.relatedServiceStableKeys],
    relatedUpdateStableKeys: [...row.relatedUpdateStableKeys],
    machineTags: [...row.machineTags],
  }))
}

export function listDeveloperRelationsForSlug(slug: string): RegistryDeveloperRelationRecord[] {
  const keys = new Set(listDeveloperResourcesForSlug(slug).map((r) => r.stableKey))
  return PROJECT_DEVELOPER_RELATIONS.filter((r) => keys.has(r.fromStableKey) && keys.has(r.toStableKey)).map((r) => ({
    ...r,
  }))
}
